#!/bin/bash
#Variables
	green='\e[1;32m'
	red='\e[1;31m'
        yellow='\e[1;33m'
        orange='\e[0;33m'
        nocolor='\e[1;m'

#Datasent you are sending from
	zfs list -t snapshot
	echo -e "$green PLEASE ENTER THE SNAPSHOT NAME YOU ARE SENDING $nocolor"
	echo -e "$green SNAPSHOTS HAVE BEEN LISTED ABOVE THAT YOU MAY COPY AND PASTE INTO THE SEND AREA $nocolor"
	echo -e "EXAMPLE: rpool/windows11@2022_07_05__05_10_07PM"
	read -p "SEND:" sendname
	echo you entered $sendname

#Network Send?
	echo -e "$yellow ARE YOU SENDING $sendname OVER AN IP VIA SSH? $nocolor"
	read -p "$(echo -e $green Y= YES IAM SENDING OVER AN IP VIA SSH $nocolor $red N= NO IAM NOT SENDING OVER SSH DEPS $nocolor)" ssh
	if [ "$ssh" = "Y" ]
		then
		echo -e "$green ENTER THE IP ADDRESS OF THE MACHINE YOU ARE SENDING TO $nocolor"
        	read -p "IP:" ip
        	echo you entered $ip
		declare ip="ssh '"$ip"'"
		else
		echo -e "$green NOT SENDING OVER AN IP / SSH $nocolor"
	fi


#Enter the destination
	echo -e "$green PLEASE ENTER THE RPOOL AND RECV NAME YOU ARE RECEIVING AT $nocolor"
	echo -e "EXAMPLE: serverpool/windows11"
	read -p "SEND:" recvname
	echo you entered $recvname

#Show selections
	declare	showselections="zfs send -c -e -v $sendname | mbuffer '-s 128k -m 1G' | $ip zfs recv $recvname"

#Declare and confirm variables
	echo -e " $red SHOULD I RUN THE FOLLOWING COMMAND: $nocolor $showselections "
	read -p "$(echo -e $green Y= YES CONTINUE $nocolor $red N= NO DO NOT CONTINUE $nocolor)" CONT
	if [ "$ssh" = "Y" ]
                then
                echo -e "$green SENDING NOW! $nocolor"
		$showselections
                else
                echo -e "$red EXITING $nocolor"
        fi

#FINISH SCRIPT
exit

