#!/bin/bash
	zpool create $@ \
	-O compression=no \
	-O dedup=no \
	-O checksum=off \
	-O recordsize=16k \
	-O dnodesize=16k \
	-O canmount=on \
	-O logbias=latency \
	-O vscan=off \
	-O volmode=full \
	-O xattr=off \
	-O acltype=nfsv4 \
	-O aclinherit=passthrough \
	-O aclmode=passthrough \
	-o ashift=12 \
	-o autoexpand=on \
	-o cachefile=/etc/zfs/zpool.cache \
	-O snapshot_limit=1950 \
	-o listsnaps=off
