#!/bin/bash
	zpool create $@ \
	-O compression=lz4 \
	-O dedup=edonr,verify \
	-O checksum=edonr \
	-O recordsize=16k \
	-O dnodesize=16k \
	-O canmount=on \
	-O logbias=latency \
	-O vscan=off \
	-O volmode=full \
	-O xattr=sa \
	-O acltype=nfsv4 \
	-O aclinherit=passthrough \
	-O aclmode=passthrough \
	-o ashift=12 \
	-o autoexpand=on \
	-o cachefile=/etc/zfs/zpool.cache \
	-O snapshot_limit=1900 \
	-o listsnaps=on
