#!/bin/bash
#This is the choosen default for the ultimate kernel builder
	zpool create $@ \
	-O compression=lz4 \
	-O checksum=off \
	-O recordsize=256k \
	-O dnodesize=legacy \
	-O canmount=on \
	-O logbias=thoughput \
	-O vscan=off \
	-O volmode=full \
	-O xattr=off \
	-O acltype=none \
	-O aclinherit=none \
	-O aclmode=none \
	-o ashift=9 \
	-o autoexpand=on \
	-o cachefile=/etc/zfs/zpool.cache \
	-o failmode=continue \
	-o listsnaps=on
