#!/bin/busybox sh
# Basic Mounting
	/bin/busybox --install
	LD_TRACE_LOADED_OBJECTS=1
	LD_LIBRARY_PATH=/lib64
	export LD_LIBRARY_PATH=/lib64
	mount -t devtmpfs none  /dev
	mount -t proc none /proc
	mount -t sysfs none /sys
	mount -t tmpfs none /tmp
	umount /dev
	LD_TRACE_LOADED_OBJECTS=1
        LD_LIBRARY_PATH=/lib64
        export LD_LIBRARY_PATH=/lib64
	PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
	TERM=linux
	echo /sbin/mdev > /proc/sys/kernel/hotplug
	mdev -s
#Declare ZFS root dataset
 	root=$(grep -o -P '(?<=root=)[^ ]+' /proc/cmdline)
	echo $root
# Do your stuff here.
	echo "Micro Initrd ZFS Script By Fixapc.net For Quick Booting And Easy Trouble Shooting"
	echo "Includes Fish Shell And A Persistent Busybox History For Usability"
	echo "Mounts devtempfs regardless of successful pool import (dracut.... initramfs-tools......)"
	echo "Can boot any fs by simply mounting it to /root and running ./init"
	echo "This init is so simple its stupid, if it does not work Its not the init, just saying....."

#Drop into shell for testing
	sh

#Importing The Pool Easy Style, the -N switch negates any mount points. So Setting mountpoint=none is not needed
	/sbin/zpool import -N -c /etc/zfs/zpool.cache

# Mount the root filesystem.
	/sbin/mount -t zfs -o zfsutil $root /root

# Clean up.
	/bin/busybox umount /proc
	/bin/busybox umount /sys

# Boot the real thing.
	echo "Booting To Root"
	/bin/busybox switch_root /root /sbin/init
