#!/bin/busybox sh
# Basic Mounting
#!/bin/sh

# shellcheck source=initrd.defaults
. /etc/initrd.defaults
# shellcheck source=initrd.scripts
. /etc/initrd.scripts

# shellcheck source=/dev/null
[ -e /etc/initrd.splash ] && . /etc/initrd.splash

# Basic /dev content, we need it as fast as possible.
[ ! -e /dev/console ]  && mknod /dev/console c 5 1
[ ! -e /dev/null ]     && mknod /dev/null c 1 3
[ ! -e /dev/random ]   && mknod /dev/random c 1 8
[ ! -e /dev/tty ]      && mknod /dev/tty c 5 0
[ ! -e /dev/tty0 ]     && mknod /dev/tty0 c 4 0
[ ! -e /dev/tty1 ]     && mknod /dev/tty1 c 4 1
[ ! -e /dev/ttyS0 ]    && mknod /dev/ttyS0 c 4 64
[ ! -e /dev/ttyS1 ]    && mknod /dev/ttyS1 c 4 65
[ ! -e /dev/urandom ]  && mknod /dev/urandom c 1 9
[ ! -e /dev/zero ]     && mknod /dev/zero c 1 5

# Take control
CONSOLE="/dev/$(get_active_console)"
exec 0<>${CONSOLE} 1<>${CONSOLE} 2<>${CONSOLE}

if [ "$$" != '1' ]
then
	echo '/linuxrc has to be run as the init process as the one'
	echo 'with a PID of 1. Try adding init="/linuxrc" to the'
	echo 'kernel command line or running "exec /linuxrc".'
	exit 1
fi

mount -t proc -o noexec,nosuid,nodev proc /proc >/dev/null 2>&1
mount -o remount,rw / >/dev/null 2>&1
mount -t tmpfs -o rw,nosuid,nodev,relatime,mode=755 none /run 2>&1

if [ ! -d /run/initramfs ]
then
	mkdir -p  /run/initramfs
	chmod 0750 /run/initramfs
fi

if [ ! -s /etc/ld.so.cache ]
then
	# Looks like we were unable to run ldconfig during initramfs generation
	hash ldconfig >/dev/null 2>&1 && run ldconfig
fi

# Set up symlinks
	run busybox --install -s

# Handle ZFS MOUNT command-line parameters
 	root=$(cat /proc/cmdline | grep -o "root=.*" | awk '{print $1}' | sed 's/root=//')

	echo $root
# Do your stuff here.
	echo "Micro Initrd ZFS Script By Fixapc.net For Quick Booting And Easy Trouble Shooting"
	echo "Includes Fish Shell And A Persistent Busybox History For Usability"
	echo "Mounts devtempfs regardless of successful pool import (dracut.... initramfs-tools......)"
	echo "Can boot any fs by simply mounting it to /root and running ./init"
	echo "This init is so simple its stupid, if it does not work Its not the init, just saying....."

#Drop into shell for testing
	sh

#Importing The Pool Easy Style, the -N switch negates any mount points. So Setting mountpoint=none is not needed
	/sbin/zpool import -N -c /etc/zfs/zpool.cache

# Mount the root filesystem.
	/sbin/mount -t zfs -o zfsutil $root /root

# Clean up.
	/bin/busybox umount /proc
	/bin/busybox umount /sys

# Boot the real thing.
	echo "Booting To Root"
	/bin/busybox switch_root /root /sbin/init
