# apt-venv
# Autogenerated from man page /usr/share/man/man1/apt-venv.1.gz
complete -c apt-venv -s h -l help -d 'show this help message and exit'
complete -c apt-venv -s D -l debug -d 'set debug level'
complete -c apt-venv -s v -l version -d 'show program\'s version number and exit'
complete -c apt-venv -s c -l command -d 'exec the given command instead of entry the interactive shell'
complete -c apt-venv -s d -l delete -d 'delete venv for release'
complete -c apt-venv -s l -l list -d 'list all venv installed in your system'

