# babeljs-node
# Autogenerated from man page /usr/share/man/man1/babeljs-node.1.gz
complete -c babeljs-node -s e -l eval -d 'Evaluate script'
complete -c babeljs-node -l no-babelrc -d 'Specify whether or not to use . babelrc and . babelignore files'
complete -c babeljs-node -s r -l require -d 'Require module'
complete -c babeljs-node -s p -l print -d 'Evaluate script and print result'
complete -c babeljs-node -s o -l only -d 'A comma-separated list of glob patterns to compile'
complete -c babeljs-node -s i -l ignore -d 'A comma-separated list of glob patterns to skip compiling'
complete -c babeljs-node -s x -l extensions -d 'List of extensions to hook into [. es6,. js,. es,. jsx,. mjs]'
complete -c babeljs-node -l config-file -d 'Path to the babel config file to use.  Defaults to working directory babel'
complete -c babeljs-node -l env-name -d 'The name of the \'env\' to use when loading configs and plugins'
complete -c babeljs-node -l root-mode -d 'The project-root resolution mode'
complete -c babeljs-node -s V -l version -d 'output the version number'
complete -c babeljs-node -s w -l plugins
complete -c babeljs-node -s b -l presets
complete -c babeljs-node -s h -l help -d 'display help for command'

