# barrierc
# Autogenerated from man page /usr/share/man/man1/barrierc.1.gz
complete -c barrierc -s d -l debug -d 'filter out log messages with priority below level'
complete -c barrierc -s n -l name -d 'this screen in the configuration'
complete -c barrierc -s 1 -l no-restart -d 'do not try to restart on failure'
complete -c barrierc -l restart -d 'restart the server automatically if it fails.  (*)'
complete -c barrierc -s l -l log -d 'write log messages to file'
complete -c barrierc -l no-tray -d 'disable the system tray icon'
complete -c barrierc -l enable-drag-drop -d 'enable file drag & drop'
complete -c barrierc -l enable-crypto -d 'enable the crypto (ssl) plugin'
complete -c barrierc -l display -d 'connect to the X server at <display>'
complete -c barrierc -l no-xinitthreads -d 'do not call XInitThreads()'
complete -c barrierc -s f -l no-daemon -d 'run in the foreground'
complete -c barrierc -l daemon -d 'run as a daemon.  (*)'
complete -c barrierc -l yscroll -d 'defines the vertical scrolling delta, which is 120 by default'
complete -c barrierc -s h -l help -d 'display this help and exit'
complete -c barrierc -l version -d 'display version information and exit'

