# bugpoint
# Autogenerated from man page /usr/share/man/man1/bugpoint.1.gz
complete -c bugpoint -o find-bugs -d 'Continually randomize the specified passes and run them on the test program u…'
complete -c bugpoint -o help -d 'Print a summary of command line options'

