# build-rdeps
# Autogenerated from man page /usr/share/man/man1/build-rdeps.1.gz
complete -c build-rdeps -s u -l update -d 'Run apt-get update before searching for build-depends'
complete -c build-rdeps -s s -l sudo -d 'Use sudo when running apt-get update.  Has no effect if -u is omitted'
complete -c build-rdeps -l distribution -d 'Select another distribution, which is searched for build-depends'
complete -c build-rdeps -l only-main -d 'Ignore contrib and non-free'
complete -c build-rdeps -l exclude-component -d 'Ignore the given component (e. g.  main, contrib, non-free)'
complete -c build-rdeps -l origin -d 'Restrict the search to only the specified origin (such as \\*(L"Debian\\*(R")'
complete -c build-rdeps -s m -l print-maintainer -d 'Print the value of the maintainer field for each package'
complete -c build-rdeps -l host-arch -d 'Explicitly set the host architecture'
complete -c build-rdeps -l build-arch -d 'Explicitly set the build architecture'
complete -c build-rdeps -l no-arch-all -l no-arch-any -d 'Ignore Build-Depends-Indep or Build-Depends-Arch while looking for reverse de…'
complete -c build-rdeps -l old -d 'Force the old simple behaviour without dose-ceve support even if dose-extra >…'
complete -c build-rdeps -l quiet -d 'Don\'t print meta information (header, counter)'
complete -c build-rdeps -s d -l debug -d 'Run the debug mode'
complete -c build-rdeps -l help -d 'Show the usage information'

