# cgclear
# Autogenerated from man page /usr/share/man/man1/cgclear.1.gz
complete -c cgclear -s l -l load -d 'specifies the config file to read'
complete -c cgclear -s L -l load-directory -d 'specifies the directory, which is searched for configuration files'
complete -c cgclear -s e -d 'specifies that only empty groups should be removed'

