# cgclassify
# Autogenerated from man page /usr/share/man/man1/cgclassify.1.gz
complete -c cgclassify -s g -d 'defines the control groups where the task will be moved'
complete -c cgclassify -l sticky -d 'If this option is used, the daemon of service cgred (cgrulesengd process) doe…'
complete -c cgclassify -l cancel-sticky -d 'If this option is used, the daemon of service cgred (cgrulesengd process) can…'

