# cgconfigparser
# Autogenerated from man page /usr/share/man/man8/cgconfigparser.8.gz
complete -c cgconfigparser -s h -l help -d 'Displays help'
complete -c cgconfigparser -s l -l load -d 'Parses the control groups configuration file Sets up the control group file s…'
complete -c cgconfigparser -s L -l load-directory -d 'Finds all files in given directory and parses them in alphabetical order like…'
complete -c cgconfigparser -s a -d 'defines the default owner of the rest of the defined control groupâs files'
complete -c cgconfigparser -s d -l dperm -d 'sets the default permissions of a control groups directory'
complete -c cgconfigparser -s f -l fperm -d 'sets the default permissions of the control group files'
complete -c cgconfigparser -s s -l tperm -d 'sets the default permissions of the control group tasks files'
complete -c cgconfigparser -s t -d 'defines the default owner of tasks file of the defined control group.  I. e'

