# cgcreate
# Autogenerated from man page /usr/share/man/man1/cgcreate.1.gz
complete -c cgcreate -s a -d 'defines the name of the user and the group which own the rest of the defined …'
complete -c cgcreate -s d -l dperm -d 'sets the permissions of a control groups directory'
complete -c cgcreate -s f -l fperm -d 'sets the permissions of the control groups parameters'
complete -c cgcreate -s g -d 'defines control groups to be added.  controllers is a list of controllers'
complete -c cgcreate -s h -l help -d 'display this help and exit'
complete -c cgcreate -s s -l tperm -d 'sets the permissions of the control group tasks file'
complete -c cgcreate -s t -d 'defines the name of the user and the group, which owns tasks file of the defi…'

