# cgdelete
# Autogenerated from man page /usr/share/man/man1/cgdelete.1.gz
complete -c cgdelete -s h -l help -d 'Display this help and exit'
complete -c cgdelete -s g -d 'is optional'
complete -c cgdelete -s r -l recursive -d 'Recursively remove all subgroups'

