# cgexec
# Autogenerated from man page /usr/share/man/man1/cgexec.1.gz
complete -c cgexec -s g -d 'defines the control groups in which the task will be run'
complete -c cgexec -s h -l help -d 'Display this help and exit'
complete -c cgexec -l sticky -d 'If running the task command with this option, the daemon of service cgred (cg…'

