# cgget
# Autogenerated from man page /usr/share/man/man1/cgget.1.gz
complete -c cgget -s a -l all -d 'print the variables for all controllers which consist in the  given cgroup'
complete -c cgget -s g -d 'defines controllers whose values should be displayed'
complete -c cgget -s h -l help -d 'display help and exit'
complete -c cgget -s n -d 'do not print headers, i. e.  names of groups'
complete -c cgget -s r -l variable -d 'defines parameter to display.  This option can be used multiple times'
complete -c cgget -s v -l values-only -d 'print only values, not parameter names'

