# cgrulesengd
# Autogenerated from man page /usr/share/man/man8/cgrulesengd.8.gz
complete -c cgrulesengd -s h -l help -d 'Display help'
complete -c cgrulesengd -s f -l logfile -d 'Write log messages to the given log file'
complete -c cgrulesengd -s s -l syslog -d 'Write log messages to syslog.  The default facility is DAEMON'
complete -c cgrulesengd -s n -l nodaemon -d 'Don\'t fork the daemon, stay in the foreground'
complete -c cgrulesengd -s v -l verbose -d 'Display more log messages'
complete -c cgrulesengd -s q -l quiet -d 'Display less log messages'
complete -c cgrulesengd -s Q -l nolog -d 'Disable logging'
complete -c cgrulesengd -s d -l debug -d 'Equivalent to \'-nvvvf -\', i. e'
complete -c cgrulesengd -s u -l socket-user
complete -c cgrulesengd -s g -l socket-group -d 'Set the owner of cgrulesengd socket'

