# cgset
# Autogenerated from man page /usr/share/man/man1/cgset.1.gz
complete -c cgset -s r -d 'defines the name of the file to set and the value which should be written to …'
complete -c cgset -l copy-from -d 'defines the name of the cgroup whose parameters will be copied to the input c…'

