# cgsnapshot
# Autogenerated from man page /usr/share/man/man1/cgsnapshot.1.gz
complete -c cgsnapshot -s b -d 'Display only variables from the blacklist'
complete -c cgsnapshot -s h -l help -d 'display this help and exit'
complete -c cgsnapshot -s f -l file -d 'Redirect the output to output_file'
complete -c cgsnapshot -s s -l silent -d 'Ignore all warnings'
complete -c cgsnapshot -s t -l strict -d 'Do not display the variables which are not on the whitelist'
complete -c cgsnapshot -s w -d 'Set the blacklist configuration file'

