# chdist
# Autogenerated from man page /usr/share/man/man1/chdist.1.gz
complete -c chdist -s h -l help -d 'Provide a usage message'
complete -c chdist -s d -l data-dir -d 'Choose data directory (default: ~/. chdist/)'
complete -c chdist -s a -l arch -d 'Choose architecture (default: `dpkg --print-architecture`)'

