# clangd
# Autogenerated from man page /usr/share/man/man1/clangd.1.gz
complete -c clangd -l enable-config -d 'Project config is from a . clangd file in the project directory'
complete -c clangd -l help -l help-hidden
complete -c clangd -l help-list -l help-list-hidden
complete -c clangd -l version
complete -c clangd -l compile-commands-dir
complete -c clangd -l query-driver
complete -c clangd -l all-scopes-completion
complete -c clangd -l background-index
complete -c clangd -l clang-tidy
complete -c clangd -l completion-style
complete -c clangd -l fallback-style
complete -c clangd -l function-arg-placeholders
complete -c clangd -l header-insertion
complete -c clangd -l header-insertion-decorators
complete -c clangd -l limit-references
complete -c clangd -l limit-results
complete -c clangd -l project-root
complete -c clangd -l remote-index-address
complete -c clangd -l check -l check
complete -c clangd -l check-lines -o check -l check-lines -l check-lines
complete -c clangd -s j
complete -c clangd -l malloc-trim
complete -c clangd -l pch-storage
complete -c clangd -l log
complete -c clangd -l offset-encoding
complete -c clangd -l path-mappings
complete -c clangd -l pretty

