# clangd-14
# Autogenerated from man page /usr/share/man/man1/clangd-14.1.gz
complete -c clangd-14 -l enable-config -d 'Project config is from a . clangd file in the project directory'
complete -c clangd-14 -l help -l help-hidden
complete -c clangd-14 -l help-list -l help-list-hidden
complete -c clangd-14 -l version
complete -c clangd-14 -l compile-commands-dir
complete -c clangd-14 -l query-driver
complete -c clangd-14 -l all-scopes-completion
complete -c clangd-14 -l background-index
complete -c clangd-14 -l clang-tidy
complete -c clangd-14 -l completion-style
complete -c clangd-14 -l fallback-style
complete -c clangd-14 -l function-arg-placeholders
complete -c clangd-14 -l header-insertion
complete -c clangd-14 -l header-insertion-decorators
complete -c clangd-14 -l limit-references
complete -c clangd-14 -l limit-results
complete -c clangd-14 -l project-root
complete -c clangd-14 -l remote-index-address
complete -c clangd-14 -l check -l check
complete -c clangd-14 -l check-lines -o check -l check-lines -l check-lines
complete -c clangd-14 -s j
complete -c clangd-14 -l malloc-trim
complete -c clangd-14 -l pch-storage
complete -c clangd-14 -l log
complete -c clangd-14 -l offset-encoding
complete -c clangd-14 -l path-mappings
complete -c clangd-14 -l pretty

