# cowpoke
# Autogenerated from man page /usr/share/man/man1/cowpoke.1.gz
complete -c cowpoke -l arch -d 'Specify the Debian architecture(s) to build for'
complete -c cowpoke -l dist -d 'Specify the Debian distribution(s) to build for'
complete -c cowpoke -l buildd -d 'Specify the remote host to build on'
complete -c cowpoke -l buildd-user -d 'Specify the remote user to build as'
complete -c cowpoke -l create -d 'Create the remote cowbuilder root if it does not already exist'
complete -c cowpoke -l return -d 'Copy results of the build to path'
complete -c cowpoke -l no-return -d 'Do not copy results of the build to RETURN_DIR (overriding a path set for it …'
complete -c cowpoke -l dpkg-opts -d 'Specify additional options to be passed to dpkg-buildpackage(1)'
complete -c cowpoke -l create-opts -d 'Specify additional arguments to be passed verbatim to cowbuilder when a chroo…'
complete -c cowpoke -l update-opts -d 'Specify additional arguments to be passed verbatim to cowbuilder if the base …'
complete -c cowpoke -l build-opts -d 'Specify additional arguments to be passed verbatim to cowbuilder when a packa…'
complete -c cowpoke -l sign -d 'Specify the key to sign packages with'
complete -c cowpoke -l upload -d 'Specify the dput queue to upload signed packages to'
complete -c cowpoke -l help -d 'Display a brief summary of the available options and current configuration'
complete -c cowpoke -l version -d 'Display the current version information'

