# cpanfile-dump.1p
# Autogenerated from man page /usr/share/man/man1/cpanfile-dump.1p.gz
complete -c 'cpanfile-dump.1p' -l configure -l build -l test -l runtime -l develop -d 'Specify the phase to include/exclude'
complete -c 'cpanfile-dump.1p' -l requires -l recommends -l suggests -l conflicts -d 'Specify the type to include/exclude'

