# cph
# Autogenerated from man page /usr/share/man/man1/cph.1.gz
complete -c cph -s h -l help -d 'show this help message and exit'
complete -c cph -s V -l version -d 'Show the conda-package-handling version number and exit. SS "subcommands:"'

