# cvs-debi
# Autogenerated from man page /usr/share/man/man1/cvs-debi.1.gz
complete -c cvs-debi -o adebian-architecture -o tGNU-system-type -d 'See dpkg-architecture(1) for a description of these options'
complete -c cvs-debi -o Mmodule -d 'The name of the CVS module'
complete -c cvs-debi -o Ppackage -d 'The name of the package'
complete -c cvs-debi -o Vversion -d 'The version number of the package'
complete -c cvs-debi -o Ttag -d 'The CVS tag to use for exporting sources'
complete -c cvs-debi -o Rrootdirectory -d 'Root of the original sources archive'
complete -c cvs-debi -o Wwork -d 'The full path name for the cvs-buildpackage working directory'
complete -c cvs-debi -o xprefix -d 'This option provides the CVS default module prefix'
complete -c cvs-debi -o Rroot -d 'Root of the original sources archive'
complete -c cvs-debi -l help -l version -d 'Show help message and version information respectively'

