# cvs-debuild
# Autogenerated from man page /usr/share/man/man1/cvs-debuild.1.gz
complete -c cvs-debuild -l no-conf -l noconf
complete -c cvs-debuild -l rootcmd -s r
complete -c cvs-debuild -l preserve-env
complete -c cvs-debuild -l preserve-envvar -s e
complete -c cvs-debuild -l set-envvar
complete -c cvs-debuild -l lintian -l no-lintian
complete -c cvs-debuild -l ignore-dirname -l check-dirname -d 'These should not be needed, but it is provided nevertheless'

