# cvs-debc
# Autogenerated from man page /usr/share/man/man1/cvs-debc.1.gz
complete -c cvs-debc -o adebian-architecture -o tGNU-system-type -d 'See dpkg-architecture(1) for a description of these options'
complete -c cvs-debc -o Mmodule -d 'The name of the CVS module'
complete -c cvs-debc -o Ppackage -d 'The name of the package'
complete -c cvs-debc -o Vversion -d 'The version number of the package'
complete -c cvs-debc -o Ttag -d 'The CVS tag to use for exporting sources'
complete -c cvs-debc -o Rrootdirectory -d 'Root of the original sources archive'
complete -c cvs-debc -o Wwork -d 'The full path name for the cvs-buildpackage working directory'
complete -c cvs-debc -o xprefix -d 'This option provides the CVS default module prefix'
complete -c cvs-debc -o Rroot -d 'Root of the original sources archive'
complete -c cvs-debc -l help -l version -d 'Show help message and version information respectively'

