# cvs-debrelease
# Autogenerated from man page /usr/share/man/man1/cvs-debrelease.1.gz
complete -c cvs-debrelease -l dupload -l dput -d 'This specifies which uploader program to use; the default is dupload'
complete -c cvs-debrelease -o adebian-architecture -o tGNU-system-type -d 'See dpkg-architecture(1) for a description of these options'
complete -c cvs-debrelease -o Mmodule -d 'The name of the CVS module'
complete -c cvs-debrelease -o Ppackage -d 'The name of the package'
complete -c cvs-debrelease -o Vversion -d 'The version number of the package'
complete -c cvs-debrelease -o Ttag -d 'The CVS tag to use for exporting sources'
complete -c cvs-debrelease -o Rrootdirectory -d 'Root of the original sources archive'
complete -c cvs-debrelease -o Wwork -d 'The full path name for the cvs-buildpackage working directory'
complete -c cvs-debrelease -o xprefix -d 'This option provides the CVS default module prefix'
complete -c cvs-debrelease -l no-conf -l noconf -d 'Do not read any configuration files'
complete -c cvs-debrelease -o Rroot -d 'Root of the original sources archive'
complete -c cvs-debrelease -l help -l version -d 'Show help message and version information respectively'

