# dcmd
# Autogenerated from man page /usr/share/man/man1/dcmd.1.gz
complete -c dcmd -l dsc -d 'Select the . dsc file'
complete -c dcmd -l schanges -d 'Select . changes files for the \'source\' architecture'
complete -c dcmd -l bchanges -d 'Select . changes files for binary architectures'
complete -c dcmd -l changes -d 'Select . changes files.  Implies --schanges and --bchanges'
complete -c dcmd -l archdeb -d 'Select architecture-dependent binary packages (. deb files)'
complete -c dcmd -l indepdeb -d 'Select architecture-independent binary packages (. deb files)'
complete -c dcmd -l deb -d 'Select binary packages (. deb files).  Implies --archdeb and --indepdeb'
complete -c dcmd -l archudeb -d 'Select architecture-dependent . udeb binary packages'
complete -c dcmd -l indepudeb -d 'Select architecture-independent . udeb binary packages'
complete -c dcmd -l udeb -d 'Select . udeb binary packages.  Implies --archudeb and --indepudeb'
complete -c dcmd -l tar -l orig -d 'Select the upstream . tar file'
complete -c dcmd -l diff -l debtar -d 'Select the Debian . debian. tar or . diff file'
complete -c dcmd -l no-fail-on-missing -s r -d 'If any of the requested files were not found, do not output an error'
complete -c dcmd -l package -s p -d 'Output package name part only'
complete -c dcmd -l sort -s s -d 'Sort output alphabetically'
complete -c dcmd -l tac -s t -d 'Reverse output order'

