# dd-list
# Autogenerated from man page /usr/share/man/man1/dd-list.1.gz
complete -c dd-list -s h -l help -d 'Print brief help message'
complete -c dd-list -s i -l stdin -d 'Read package names from the standard input, instead of taking them from the c…'
complete -c dd-list -s d -l dctrl -d 'Read package list from standard input in the format of a Debian package contr…'
complete -c dd-list -s z -l uncompress -d 'Try to uncompress the --dctrl input before parsing'
complete -c dd-list -s s -l sources -d 'Read package information from the specified Sources_files'
complete -c dd-list -s u -l uploaders -d 'Also list developers who are named as uploaders of packages, not only the mai…'
complete -c dd-list -o nou -l nouploaders -d 'Only list package Maintainers, do not list Uploaders'
complete -c dd-list -s b -l print-binary -d 'Use binary package names in the output instead of source package names (has n…'
complete -c dd-list -s V -l version -d 'Print the version'

