# deb-janitor
# Autogenerated from man page /usr/share/man/man1/deb-janitor.1.gz
complete -c deb-janitor -s h -l help -d 'show this help message and exit'
complete -c deb-janitor -s v -l verbose -d 'Output more information'
complete -c deb-janitor -l api-url -d 'Override the API endpoint to communicate with, rather than using the main Deb…'
complete -c deb-janitor -l - -d '+++ b/debian/upstream/metadata	2020-11-28 11:58:34 +0000 @@ -0,0 +1,5 @@ +---…'

