# deb-reversion
# Autogenerated from man page /usr/share/man/man1/deb-reversion.1.gz
complete -c deb-reversion -s v -l new-version -d 'Specifies the version number to be used for the new version'
complete -c deb-reversion -s o -l old-version -d 'Specifies the version number to be used as the old version instead of the ver…'
complete -c deb-reversion -s c -l calculate-only -d 'Only calculate and display the new version number which would be used; do not…'
complete -c deb-reversion -s s -l string -d 'Instead of using \\*(AqLOCAL'
complete -c deb-reversion -s k -l hook -d 'A hook command to run after unpacking the old '
complete -c deb-reversion -s D -l debug -d 'Pass --debug to dpkg-deb(1)'
complete -c deb-reversion -s b -l force-bad-version -d 'Pass --force-bad-version to dch(1)'
complete -c deb-reversion -s h -l help -d 'Display usage information'
complete -c deb-reversion -s V -l version -d 'Display version information'
complete -c deb-reversion -s a -d 'deb-reversion command line and dch will be called automatically'

