# deb-why-removed
# Autogenerated from man page /usr/share/man/man1/deb-why-removed.1.gz
complete -c deb-why-removed -s u -l url -d '\\s-1URL\\s0 to the archive removals deb822-formatted file list'
complete -c deb-why-removed -l no-refresh -d 'Do not refresh the cached removals file even if there is a newer version in t…'
complete -c deb-why-removed -s h -s '?' -l help -d 'Show a help message and exit'

