# debclean
# Autogenerated from man page /usr/share/man/man1/debclean.1.gz
complete -c debclean -l cleandebs -d 'Also remove all . deb, . changes and . build files from the parent directory'
complete -c debclean -l nocleandebs -d 'Do not remove the . deb, . changes and '
complete -c debclean -l check-dirname-level -d 'See the above section Directory name checking for an explanation of this opti…'
complete -c debclean -l check-dirname-regex -d 'See the above section Directory name checking for an explanation of this opti…'
complete -c debclean -l no-conf -l noconf -d 'Do not read any configuration files'
complete -c debclean -s d -d 'Do not run dpkg-checkbuilddeps to check build dependencies'
complete -c debclean -l help -d 'Display a help message and exit successfully'
complete -c debclean -l version -d 'Display version and copyright information and exit successfully'

