# debc
# Autogenerated from man page /usr/share/man/man1/debc.1.gz
complete -c debc -o adebian-architecture -o tGNU-system-type -d 'See dpkg-architecture(1) for a description of these options'
complete -c debc -l debs-dir -d 'Look for the . changes, . deb and '
complete -c debc -l check-dirname-level -d 'See the above section Directory name checking for an explanation of this opti…'
complete -c debc -l check-dirname-regex -d 'See the above section Directory name checking for an explanation of this opti…'
complete -c debc -l list-changes -d 'List the filename of the . changes file, and do not display anything else'
complete -c debc -l list-debs -d 'List the filenames of the . deb packages, and do not display their contents'
complete -c debc -l no-conf -l noconf -d 'Do not read any configuration files'
complete -c debc -l help -l version -d 'Show help message and version information respectively'

