# debcheckout
# Autogenerated from man page /usr/share/man/man1/debcheckout.1.gz
complete -c debcheckout -s a -l auth -d 'Work in authenticated mode; this means that for known repositories (mainly th…'
complete -c debcheckout -s d -l details -d 'Only print a list of detailed information about the package repository, witho…'
complete -c debcheckout -s h -l help -d 'Print a detailed help message and exit'
complete -c debcheckout -s p -l print -d 'Only print a summary about package repository information, without checking i…'
complete -c debcheckout -s P -l package -d 'When checking out a repository \\s-1URL,\\s0 instead of trying to guess the pac…'
complete -c debcheckout -s t -l type -d 'Override the repository type (which defaults to some heuristics based on the …'
complete -c debcheckout -s u -l user -d 'Specify the login name to be used in authenticated mode (see -a)'
complete -c debcheckout -s f -l file -d 'Specify that the named file should be extracted from the repository and place…'
complete -c debcheckout -l source -d 'Some packages only place the debian directory in version control'

