# debi
# Autogenerated from man page /usr/share/man/man1/debi.1.gz
complete -c debi -o adebian-architecture -o tGNU-system-type -d 'See dpkg-architecture(1) for a description of these options'
complete -c debi -l debs-dir -d 'Look for the . changes and '
complete -c debi -s m -l multi -d 'Search for a multiarch . changes file, as created by dpkg-cross'
complete -c debi -s u -l upgrade -d 'Only upgrade packages already installed on the system, rather than installing…'
complete -c debi -l check-dirname-level -d 'See the above section Directory name checking for an explanation of this opti…'
complete -c debi -l check-dirname-regex -d 'See the above section Directory name checking for an explanation of this opti…'
complete -c debi -l with-depends -d 'Attempt to satisfy the Depends of a package when installing it'
complete -c debi -l tool -d 'Use the specified tool for installing the dependencies of the package(s) to b…'
complete -c debi -l no-conf -l noconf -d 'Do not read any configuration files'
complete -c debi -l help -l version -d 'Show help message and version information respectively'

