# debootsnap
# Autogenerated from man page /usr/share/man/man1/debootsnap.1.gz
complete -c debootsnap -s h -l help -d 'show this help message and exit'
complete -c debootsnap -l architecture -l nativearch -d 'native architecture of the chroot.  Ignored if --buildinfo is used'
complete -c debootsnap -l ignore-notfound -d 'only warn about packages that cannot be found on snapshot. debian'
complete -c debootsnap -l buildinfo -d 'use packages from a buildinfo file'
complete -c debootsnap -l packages -l pkgs -d 'list of packages, optional architecture and version, separated by comma or li…'
complete -c debootsnap -l sources-list-only -d 'only query metasnap. debian. net and print the sources'

