# debrsign
# Autogenerated from man page /usr/share/man/man1/debrsign.1.gz
complete -c debrsign -s S -d 'Look for a source-only . changes file instead of a binary-build '
complete -c debrsign -o adebian-architecture -o tGNU-system-type -d 'See dpkg-architecture(1) for a description of these options'
complete -c debrsign -l multi -d 'Multiarch '
complete -c debrsign -l path -d 'Specify a path to the GPG binary on the remote host'
complete -c debrsign -l help -l version -d 'Show help message and version information respectively'

