# debrebuild
# Autogenerated from man page /usr/share/man/man1/debrebuild.1.gz
complete -c debrebuild -l help -s h -d 'Show this help and exit'
complete -c debrebuild -l use-tor-proxy -d 'Whether to fetch resources via tor (socks://127. 0. 0'
complete -c debrebuild -l respect-build-path -d 'Whether to setup the build to use the Build-Path from the provided '
complete -c debrebuild -l buildresults -d 'Directory for the build artifacts (default: . /)'
complete -c debrebuild -l builder -d 'Which building software should be used'

