# debrepro
# Autogenerated from man page /usr/share/man/man1/debrepro.1.gz
complete -c debrepro -s s -l skip -d 'Don\'t perform the named \\s-1VARIATION'
complete -c debrepro -s b -l before-second-build -d 'Run \\s-1COMMAND\\s0 before performing the second build'
complete -c debrepro -s B -l build-command -d 'Use custom build command.  Default: dpkg-buildpackage -b -us -uc'
complete -c debrepro -s a -l artifact-pattern -d 'Define a file glob pattern to determine which artifacts need to be compared a…'
complete -c debrepro -s n -l no-copy -d 'Do not copy the source directory to the temporary work directory before each …'
complete -c debrepro -s t -l timeout -d 'Apply a timeout to all builds'

