# debrelease
# Autogenerated from man page /usr/share/man/man1/debrelease.1.gz
complete -c debrelease -l dupload -l dput -d 'This specifies which uploader program to use; the default is dupload'
complete -c debrelease -s S -d 'If this option is used, or the default '
complete -c debrelease -o adebian-architecture -o tGNU-system-type -d 'See dpkg-architecture(1) for a description of these options'
complete -c debrelease -l multi -d 'Multiarch '
complete -c debrelease -l debs-dir -d 'Look for the . changes and '
complete -c debrelease -l check-dirname-level -d 'See the above section Directory name checking for an explanation of this opti…'
complete -c debrelease -l check-dirname-regex -d 'See the above section Directory name checking for an explanation of this opti…'
complete -c debrelease -l no-conf -l noconf -d 'Do not read any configuration files'
complete -c debrelease -l help -s h -d 'Display a help message and exit successfully'
complete -c debrelease -l version -d 'Display version and copyright information and exit successfully'

