# debsnap
# Autogenerated from man page /usr/share/man/man1/debsnap.1.gz
complete -c debsnap -s d -l destdir -d 'Directory to place retrieved packages'
complete -c debsnap -s f -l force -d 'Force writing into an existing destination'
complete -c debsnap -s v -l verbose -d 'Report on the debsnap configuration being used and progress during the downlo…'
complete -c debsnap -s l -l list -d 'Don\'t download but just list versions'
complete -c debsnap -l binary -d 'Download binary packages instead of source packages'
complete -c debsnap -s a -l architecture -d 'Specify architecture of downloaded binary packages.  Implies --binary'
complete -c debsnap -l first -d 'Specify the minimum version of a package which will be downloaded'
complete -c debsnap -l last -d 'Specify the maximum version of a package which will be downloaded'
complete -c debsnap -s h -l help -d 'Show a summary of these options'
complete -c debsnap -l version -d 'Show the version of debsnap'

