# debsign
# Autogenerated from man page /usr/share/man/man1/debsign.1.gz
complete -c debsign -s r -d 'The files to be signed live on the specified remote host.   In this case, a '
complete -c debsign -o pprogname -d 'When debsign needs to execute GPG to sign it will run progname (searching the…'
complete -c debsign -o mmaintainer -d 'Specify the maintainer name to be used for signing'
complete -c debsign -o emaintainer -d 'Same as -m but takes precedence over it'
complete -c debsign -o kkeyid -d 'Specify the key ID to be used for signing; overrides any -m and -e options'
complete -c debsign -s S -d 'Look for a source-only . changes file instead of a binary-build '
complete -c debsign -o adebian-architecture -o tGNU-system-type -d 'See dpkg-architecture(1) for a description of these options'
complete -c debsign -l multi -d 'Multiarch '
complete -c debsign -l re-sign -l no-re-sign -d 'Recreate signature, respectively use the existing signature, if the file has …'
complete -c debsign -l debs-dir -d 'Look for the files to be signed in directory DIR instead of the parent of the…'
complete -c debsign -l no-conf -l noconf -d 'Do not read any configuration files'
complete -c debsign -l help -s h -d 'Display a help message and exit successfully'
complete -c debsign -l version -d 'Display version and copyright information and exit successfully'

