# deluser
# Autogenerated from man page /usr/share/man/man8/deluser.8.gz
complete -c deluser -l conf -s c -d 'Use file instead of the default files /etc/deluser. conf and /etc/adduser'
complete -c deluser -l group -d 'Remove a group'
complete -c deluser -l help -s h -d 'Display brief instructions'
complete -c deluser -l quiet -s q -d 'Suppress progress messages'
complete -c deluser -l debug -d 'Be verbose, most useful if you want to nail down a problem'
complete -c deluser -l system -d 'Only delete if user/group is a system user/group'
complete -c deluser -l only-if-empty -d 'Only remove if no members are left'
complete -c deluser -l backup -d 'Backup all files contained in the userhome and the mailspool file to a file n…'
complete -c deluser -l backup-to -d 'Place the backup files not in the current directory but in dir'
complete -c deluser -l remove-home -d 'Remove the home directory of the user and its mailspool'
complete -c deluser -l remove-all-files -d 'Remove all files from the system owned by this user'
complete -c deluser -l no-preserve-root -d 'user by accident'
complete -c deluser -l version -d 'Display version and copyright information.  RETURN VALUE'

