# dep3changelog
# Autogenerated from man page /usr/share/man/man1/dep3changelog.1.gz
complete -c dep3changelog -l help -s h -d 'Display a help message and exit successfully'
complete -c dep3changelog -l version -d 'Display version and copyright information and exit successfully.  ENVIRONMENT'

