# dget
# Autogenerated from man page /usr/share/man/man1/dget.1.gz
complete -c dget -s a -l all -d 'Interpret package as a source package name, and download all binaries as foun…'
complete -c dget -s b -l backup -d 'Move files that would be overwritten to . /backup'
complete -c dget -s q -l quiet -d 'Suppress wget/curl non-error output'
complete -c dget -s d -l download-only -d 'Do not run dpkg-source -x on the downloaded source package'
complete -c dget -s x -l extract -d 'Run dpkg-source -x on the downloaded source package to unpack it'
complete -c dget -s u -l allow-unauthenticated -d 'Do not attempt to verify the integrity of downloaded source packages using ds…'
complete -c dget -l build -d 'Run dpkg-buildpackage -b -uc on the downloaded source package'
complete -c dget -l path -d 'In addition to /var/cache/apt/archives, dget uses the colon-separated list gi…'
complete -c dget -l insecure -d 'Allow \\s-1SSL\\s0 connections to untrusted hosts'
complete -c dget -l no-cache -d 'Bypass server-side \\s-1HTTP\\s0 caches by sending a Pragma: no-cache header'
complete -c dget -s h -l help -d 'Show a help message'

