# dh-dzil-refresh
# Autogenerated from man page /usr/share/man/man1/dh-dzil-refresh.1.gz
complete -c dh-dzil-refresh -s w -l wrap-and-sort -d el
complete -c dh-dzil-refresh -s a -l wrap-and-sort-always -d el
complete -c dh-dzil-refresh -s c -l clean-backup-files -d el

