# dh_installchangelogs
# Autogenerated from man page /usr/share/man/man1/dh_installchangelogs.1.gz
complete -c dh_installchangelogs -s k -l keep -d 'Keep the original name of the upstream changelog'
complete -c dh_installchangelogs -o Xitem -l exclude -d 'Exclude upstream changelog files that contain item anywhere in their filename…'

