# dh_makefont
# Autogenerated from man page /usr/share/man/man1/dh_makefont.1.gz
complete -c dh_makefont -s h -l help -d 'Display the name, version, available options and authors, and exit successful…'
complete -c dh_makefont -s c -l copyright -d 'Use license in copyright file for the package'
complete -c dh_makefont -s p -l package -d 'Force package name to be name'
complete -c dh_makefont -l maint -d 'Override the default name of the maintainer from "Debian Fonts Task Force" to…'
complete -c dh_makefont -s u -l upstream -d 'Set the url from where the fonts were downloaded from to url'
complete -c dh_makefont -s v -l version -d 'Show the version number of program and exit'

