# dmenu_run
# Autogenerated from man page /usr/share/man/man1/dmenu_run.1.gz
complete -c dmenu_run -s b -d 'dmenu appears at the bottom of the screen'
complete -c dmenu_run -s f -d 'dmenu grabs the keyboard before reading stdin if not reading from a tty'
complete -c dmenu_run -s i -d 'dmenu matches menu items case insensitively'
complete -c dmenu_run -s l -d 'dmenu lists items vertically, with the given number of lines'
complete -c dmenu_run -s m -d 'dmenu is displayed on the monitor number supplied'
complete -c dmenu_run -s p -d 'defines the prompt to be displayed to the left of the input field'
complete -c dmenu_run -o fn -d 'defines the font or font set used'
complete -c dmenu_run -o nb -d 'defines the normal background color'
complete -c dmenu_run -o nf -d 'defines the normal foreground color'
complete -c dmenu_run -o sb -d 'defines the selected background color'
complete -c dmenu_run -o sf -d 'defines the selected foreground color'
complete -c dmenu_run -s v -d 'prints version information to stdout, then exits'
complete -c dmenu_run -s w -d 'embed into windowid.  USAGE dmenu is completely controlled by the keyboard'

