# dscverify
# Autogenerated from man page /usr/share/man/man1/dscverify.1.gz
complete -c dscverify -l keyring -d 'Add keyring to the list of keyrings to be used'
complete -c dscverify -l no-default-keyrings -d 'Do not use the default set of keyrings'
complete -c dscverify -l no-conf -l noconf -d 'Do not read any configuration files'
complete -c dscverify -l nosigcheck -l no-sig-check -s u -d 'Skip the signature verification step'
complete -c dscverify -l verbose -d 'Do not suppress GPG output'
complete -c dscverify -l help -s h -d 'Display a help message and exit successfully'
complete -c dscverify -l version -d 'Display version and copyright information and exit successfully'

