# edac-util
# Autogenerated from man page /usr/share/man/man1/edac-util.1.gz
complete -c edac-util -s h -l help -d 'Display a summary of the command-line options'
complete -c edac-util -s q -l quiet -d 'Quiet mode'
complete -c edac-util -s v -l verbose -d 'Increase verbosity.  Multiple -v\'s may be used'
complete -c edac-util -s s -l status -d 'Displays the current status of EDAC drivers'
complete -c edac-util -s r -l report -d 'Specify the report to generate'

