# edac-ctl
# Autogenerated from man page /usr/share/man/man8/edac-ctl.8.gz
complete -c edac-ctl -l help -d 'Display a brief usage message'
complete -c edac-ctl -l mainboard -d 'Print mainboard vendor and model for this hardware, if available'
complete -c edac-ctl -l status -d 'Print the status of EDAC drivers (loaded or unloaded)'
complete -c edac-ctl -l register-labels -d 'Register motherboard DIMM labels into EDAC driver sysfs files'
complete -c edac-ctl -l print-labels -d 'Display the configured labels for the current hardware, as well as the curren…'
complete -c edac-ctl -l labeldb -d 'Specify an alternate location for the labels database'

