# equivs-build
# Autogenerated from man page /usr/share/man/man1/equivs-build.1.gz
complete -c equivs-build -l full -s f -d 'Do a complete build'
complete -c equivs-build -l source -s s -d 'Do a source build'
complete -c equivs-build -l arch -s a -d 'Build package for the specified architecture.  Used e. g'

