# esparse
# Autogenerated from man page /usr/share/man/man1/esparse.1.gz
complete -c esparse -l comment -d 'Gather all line and block comments in an array'
complete -c esparse -l loc -d 'Include line-column location info for each syntax node'
complete -c esparse -l range -d 'Include index-based range for each syntax node'
complete -c esparse -l raw -d 'Display the raw value of literals'
complete -c esparse -l tokens -d 'List all tokens in an array'
complete -c esparse -l tolerant -d 'Tolerate errors on a best-effort basis (experimental)'
complete -c esparse -s v -l version -d 'Shows program version'

