# esvalidate
# Autogenerated from man page /usr/share/man/man1/esvalidate.1.gz
complete -c esvalidate -l format -d 'Set the report format, plain (default) or junit'
complete -c esvalidate -s v -l version -d 'Print program version'

