# fzy
# Autogenerated from man page /usr/share/man/man1/fzy.1.gz
complete -c fzy -s l -l lines -d 'How many lines of items to display.  If unspecified, defaults to 10 lines'
complete -c fzy -s p -l prompt -d 'Input prompt (default: \'> \') '
complete -c fzy -s s -l show-scores -d 'Show the scores for each item'
complete -c fzy -s t -l tty -d 'Use TTY instead of the default tty device (/dev/tty)'
complete -c fzy -s q -l query -d 'Use QUERY as the initial search query'
complete -c fzy -s e -l show-matches -d 'Non-interactive mode.  Print the matches in sorted order for QUERY to stdout'
complete -c fzy -s h -l help -d 'Usage help'
complete -c fzy -s v -l version -d 'Usage help'

