# gdm-control
# Autogenerated from man page /usr/share/man/man1/gdm-control.1.gz
complete -c gdm-control -l help -d 'Display some help and exit'
complete -c gdm-control -l none -d 'Do nothing special when the current session ends'
complete -c gdm-control -l shutdown -d 'Shutdown the computer when the current session ends'
complete -c gdm-control -l reboot -d 'eboot the computer when the current session ends'
complete -c gdm-control -l suspend -d 'Suspend the computer when the current session ends'

