# getbuildlog
# Autogenerated from man page /usr/share/man/man1/getbuildlog.1.gz
complete -c getbuildlog -s h -l help -d 'Show usage information and examples'
complete -c getbuildlog -s V -l version -d 'Show version and copyright information.  EXAMPLES'

