# git-deborig
# Autogenerated from man page /usr/share/man/man1/git-deborig.1.gz
complete -c git-deborig -s f -l force -d 'Overwrite any existing orig. tar in the parent directory'
complete -c git-deborig -l just-print -d 'Instead of actually invoking git-archive\\|(1), output information about how i…'
complete -c git-deborig -l just-print-tag-names -d 'Instead of actually invoking git-archive\\|(1), or even checking which tags ex…'

