# grc
# Autogenerated from man page /usr/share/man/man1/grc.1.gz
complete -c grc -l help -d 'Show summary of options'
complete -c grc -l version -d 'Display version'
complete -c grc -s e -l stderr -d 'Redirect error output'
complete -c grc -s s -l stdout -d 'Redirect standard output'
complete -c grc -l colour -d 'x is one of on off auto'

