# grep-excuses
# Autogenerated from man page /usr/share/man/man1/grep-excuses.1.gz
complete -c grep-excuses -l no-conf -l noconf -d 'Do not read any configuration files'
complete -c grep-excuses -l wipnity -s w -d 'Get information from <https://qa. debian. org/excuses. php>'
complete -c grep-excuses -l help -d 'Show a brief usage message'
complete -c grep-excuses -l version -d 'Show version and copyright information'
complete -c grep-excuses -l autopkgtests -d 'Investigate and show autopkgtest (ci. debian'
complete -c grep-excuses -l no-autoremovals -d 'Investigate and show only testing propagation excuses, not autoremovals'
complete -c grep-excuses -l debug -d 'Print debugging output to stderr (including url(s) fetched)'

