# hardening-check
# Autogenerated from man page /usr/share/man/man1/hardening-check.1.gz
complete -c hardening-check -l nopie -s p -d 'Do not require that the checked binaries be built as \\s-1PIE. \\s0'
complete -c hardening-check -l nostackprotector -s s -d 'Do not require that the checked binaries be built with the stack protector'
complete -c hardening-check -l nofortify -s f -d 'Do not require that the checked binaries be built with Fortify Source'
complete -c hardening-check -l norelro -s r -d 'Do not require that the checked binaries be built with \\s-1RELRO. \\s0'
complete -c hardening-check -l nobindnow -s b -d 'Do not require that the checked binaries be built with \\s-1BIND_NOW. \\s0'
complete -c hardening-check -l nocfprotection -d 'Do not require that the checked binaries be built with control flow protection'
complete -c hardening-check -l quiet -s q -d 'Only report failures'
complete -c hardening-check -l verbose -s v -d 'Report verbosely on failures'
complete -c hardening-check -l report-functions -s R -d 'After the report, display all external functions needed by the \\s-1ELF. \\s0'
complete -c hardening-check -l find-libc-functions -s F -d 'Instead of the regular report, locate the libc for the first \\s-1ELF\\s0 on th…'
complete -c hardening-check -l color -s c -d 'Enable colorized status output'
complete -c hardening-check -l lintian -s l -d 'Switch reporting to lintian-check-parsable output'
complete -c hardening-check -l debug -d 'Report some debugging during processing'
complete -c hardening-check -l help -s h -s '?' -d 'Print a brief help message and exit'

