# i3blocks
# Autogenerated from man page /usr/share/man/man1/i3blocks.1.gz
complete -c i3blocks -s c -d 'Specifies an alternate configuration file path'
complete -c i3blocks -s v -d 'Log level.  This option is cumulative'
complete -c i3blocks -s V -d 'Print the version and exit. RS . RE'
complete -c i3blocks -s h -d 'Print the help message and exit.  CONFIGURATION'

