# idle-python3.11
# Autogenerated from man page /usr/share/man/man1/idle-python3.11.1.gz
complete -c 'idle-python3.11' -s h -d 'PD Print this help message and exit'
complete -c 'idle-python3.11' -s n -d 'PD Run IDLE without a subprocess (see Help/IDLE Help for details)'
complete -c 'idle-python3.11' -s e -d 'PD Open an edit window'
complete -c 'idle-python3.11' -s i -d 'PD Open a shell window'
complete -c 'idle-python3.11' -s c -d 'PD Run the command in a shell, or'
complete -c 'idle-python3.11' -s r -d 'PD Run script from file. PP'
complete -c 'idle-python3.11' -s d -d 'PD Enable the debugger'
complete -c 'idle-python3.11' -s s -d 'PD Run $IDLESTARTUP or $PYTHONSTARTUP before anything else'
complete -c 'idle-python3.11' -s t

