# ipmilan
# Autogenerated from man page /usr/share/man/man8/ipmilan.8.gz
complete -c ipmilan -s c -d 'Set the configuration file to one other than the default of  "/etc/ipmi_lan'
complete -c ipmilan -s n -d 'Stops  the  daemon  from  forking  and  detaching  from the controlling termi…'
complete -c ipmilan -s d -d 'Turns on debugging to standard output.   You generally have to use'

