# ipmi_ui
# Autogenerated from man page /usr/share/man/man1/ipmi_ui.1.gz
complete -c ipmi_ui -o dmsg -d 'Turn on message debugging, this will dump all messages to the log window'
complete -c ipmi_ui -o dmem -d 'Turn on memory debugging, this will cause memory allocation and deallocations…'
complete -c ipmi_ui -o snmp -d 'Enable the SNMP trap handler'
complete -c ipmi_ui -s c -d 'Run the program in command-line mode.   This is useful for scripting'

