# ipmish
# Autogenerated from man page /usr/share/man/man1/ipmish.1.gz
complete -c ipmish -l dmsg -d 'Turn on message debugging, this will dump all messages to debug log output'
complete -c ipmish -l drawmsg -d 'Turn on raw message debugging, this will dump all low-level messages to debug…'
complete -c ipmish -l dmem -d 'Turn on memory debugging, this will cause memory allocation and deallocations…'
complete -c ipmish -l dlock -d 'Turn on lock debugging, this will check lock operations to make sure that loc…'
complete -c ipmish -l snmp -d 'Enable the SNMP trap handler'
complete -c ipmish -l help -d 'Help output'

