# ipmi_sim
# Autogenerated from man page /usr/share/man/man1/ipmi_sim.1.gz
complete -c ipmi_sim -s c -d 'Set the configuration file to one other than the default of  "/etc/ipmi/lan'
complete -c ipmi_sim -s f -d 'Specify a command file to execute when  ipmi_sim is starting'
complete -c ipmi_sim -s x -d 'Execute a single command'
complete -c ipmi_sim -s s -d 'Specify a state directory for  ipmi_sim to use instead of the default'
complete -c ipmi_sim -s d -d 'Turns on debugging to standard output (if -n is not specified) and the debug …'
complete -c ipmi_sim -s n -d 'Disables console and I/O on standard input and output'

