# js-yaml
# Autogenerated from man page /usr/share/man/man1/js-yaml.1.gz
complete -c js-yaml -s h -l help -d 'show this help message and exit'
complete -c js-yaml -s v -l version -d 'show program\'s version number and exit'
complete -c js-yaml -s c -l compact -d 'Display errors in compact mode'
complete -c js-yaml -s t -l trace -d 'Show stack trace on error AUTHORS js-yaml was primarily authored by Vladimir …'

