# json5
# Autogenerated from man page /usr/share/man/man1/json5.1.gz
complete -c json5 -s s -l space -d 'The number of spaces to indent or \'t\' for tabs'
complete -c json5 -s o -l out-file -d 'Output to the specified file, otherwise STDOUT'
complete -c json5 -s v -l validate -d 'Validate JSON5 but do not output JSON'
complete -c json5 -s V -l version -d 'Output the version number'
complete -c json5 -s h -l help -d 'Output usage information'

