# ksh93
# Autogenerated from man page /usr/share/man/man1/ksh93.1.gz
complete -c ksh93 -s l -d 'option of the kill built-in utility)'
complete -c ksh93 -s p -d 'option of the built-in commands read and print described later'
complete -c ksh93 -s a -d 'option to typeset.  Indexed arrays need not be declared'
complete -c ksh93 -s A -d 'option to typeset'
complete -c ksh93 -s n -d 'attribute of typeset '
complete -c ksh93 -s E
complete -c ksh93 -s F -d or
complete -c ksh93 -s X -d 'or the integer attribute,'
complete -c ksh93 -s i -d 'is set for vname , then the value is subject to arithmetic evaluation as desc…'
complete -c ksh93 -s u -d 'attribute is referenced and when a command is not found'
complete -c ksh93 -s 1 -d otherwise
complete -c ksh93 -s f -d 'option has been set'
complete -c ksh93 -s b -d 'True, if file exists and is a block special file'
complete -c ksh93 -s c -d 'True, if file exists and is a character special file'
complete -c ksh93 -s d -d 'True, if file exists and is a directory'
complete -c ksh93 -s e -d 'True, if file exists'
complete -c ksh93 -s g -d 'True, if file exists and it has its setgid bit set'
complete -c ksh93 -s k -d 'True, if file exists and it has its sticky bit set'
complete -c ksh93 -s o -d 'True, if option named option is a valid option name'
complete -c ksh93 -s r -d 'True, if file exists and is readable by current process'
complete -c ksh93 -s s -d 'True, if file exists and has size greater than zero'
complete -c ksh93 -s t -d 'True, if file descriptor number fildes is open and associated with a terminal…'
complete -c ksh93 -s v -d 'True, if variable name is a valid variable name and is set'
complete -c ksh93 -s w -d 'True, if file exists and is writable by current process'
complete -c ksh93 -s x -d 'True, if file exists and is executable by current process'
complete -c ksh93 -s z -d 'True, if length of string is zero'
complete -c ksh93 -s L -d 'True, if file exists and is a symbolic link'
complete -c ksh93 -s h -d 'True, if file exists and is a symbolic link'
complete -c ksh93 -s N -d 'True, if file exists and the modification time is greater than the last acces…'
complete -c ksh93 -s O -d 'True, if file exists and is owned by the effective user ID of this process'
complete -c ksh93 -s G -d 'True, if file exists and its group matches the effective group ID of this pro…'
complete -c ksh93 -s R -d 'True if variable name is a name reference'
complete -c ksh93 -s S -d 'True, if file exists and is a socket'
complete -c ksh93 -s T -d 'option of the typeset built-in command.  With the'
complete -c ksh93 -l man -d 'option or any of the other'
complete -c ksh93 -s y -d 'Equivalent to 0-y'
complete -c ksh93 -l help -d 'as a request to display the OPTIONS section from their manual page, and'
complete -c ksh93 -s '?' -d 'as a request to print a brief usage message'
complete -c ksh93 -s P -d 'option causes symbolic links to be resolved when determining the directory'
complete -c ksh93 -s V -d 'option causes command to act like whence -v .  Without the'
complete -c ksh93 -s C
complete -c ksh93 -s B -d 'Enable brace group expansion'
complete -c ksh93 -s H -d 'Enable !-style history expansion similar to csh (1)'
complete -c ksh93 -s m -d 'Background jobs will run in a separate process group and a line will print up…'
complete -c ksh93 -o eq
complete -c ksh93 -o ne
complete -c ksh93 -o gt
complete -c ksh93 -o ge
complete -c ksh93 -o lt -d and
complete -c ksh93 -o le -d 'of the test/[ built-in command, causing them to accept only decimal numbers a…'
complete -c ksh93 -s M -d 'Use the character mapping mapping defined by wctrans (3)'
complete -c ksh93 -s Z -d 'Right justify and fill with leading zeros if the first non-blank character is…'
complete -c ksh93 -s q -d 'The message queue size in K-bytes'
complete -c ksh93 -s D -d 'A list of all double quoted strings that are preceded by a $ will be printed …'
complete -c ksh93 -l rc -d 'Read the file named by the ENV variable or by $HOME/'
complete -c ksh93 -l norc -d 'to turn off'
complete -c ksh93 -l interactive -d 'If the'
complete -c ksh93 -l restricted -d 'If the'

