# libvirt-dbus
# Autogenerated from man page /usr/share/man/man8/libvirt-dbus.8.gz
complete -c libvirt-dbus -s h -l help -d 'Display command line help usage then exit'
complete -c libvirt-dbus -l system -d 'Connect to the system bus'
complete -c libvirt-dbus -l session -d 'Connect to the session bus'
complete -c libvirt-dbus -s t -l threads -d 'Configure maximal number of worker threads'

