# list-unreleased
# Autogenerated from man page /usr/share/man/man1/list-unreleased.1.gz
complete -c list-unreleased -s c -d 'Display pending changes'
complete -c list-unreleased -s R -d 'Don\'t recurse into subdirectories looking for packages'

