# llvm-extract
# Autogenerated from man page /usr/share/man/man1/llvm-extract.1.gz
complete -c llvm-extract -s f -d 'Enable binary output on terminals'
complete -c llvm-extract -o help -d 'Print a summary of command line options'
complete -c llvm-extract -s o -d 'Specify the output filename'
complete -c llvm-extract -s S -d 'Write output in LLVM intermediate language (instead of bitcode).  EXIT STATUS'

