# lssubsys
# Autogenerated from man page /usr/share/man/man1/lssubsys.1.gz
complete -c lssubsys -s m -l mount-points -d 'Display mount points'
complete -c lssubsys -s M -l all-mount-points -d 'Display mount points'
complete -c lssubsys -s a -l all -d 'Display all subsystems (including unmounted ones)'
complete -c lssubsys -s i -l hierarchies -d 'Display the attached hierarchy number if the subsystem is in a hierarchy'
complete -c lssubsys -s h -l help -d 'Display help and exit'

