# manpage-alert
# Autogenerated from man page /usr/share/man/man1/manpage-alert.1.gz
complete -c manpage-alert -s h -l help -d 'Show a summary of options'
complete -c manpage-alert -s V -l version -d 'Show version and copyright information'
complete -c manpage-alert -s f -l file -d 'Show filenames of missing manpages without any leading text'
complete -c manpage-alert -s p -l package -d 'Show filenames of missing manpages with their package name'
complete -c manpage-alert -s n -l no-stat -d 'Do not show statistics at the end'

