# markdown_py
# Autogenerated from man page /usr/share/man/man1/markdown_py.1.gz
complete -c markdown_py -l version -d 'Show program\'s version number and exit'
complete -c markdown_py -s h -l help -d 'Show the help message and exit'
complete -c markdown_py -s f -l file -d 'Write output to OUTPUT_FILE.  Defaults to STDOUT'
complete -c markdown_py -s e -l encoding -d 'Encoding for input and output files'
complete -c markdown_py -s o -l output_format -d 'Use output format \'xhtml\' (default) or \'html\''
complete -c markdown_py -s n -l no_lazy_ol -d 'Observe number of first item of ordered lists'
complete -c markdown_py -s x -l extension -d 'Load extension EXTENSION'
complete -c markdown_py -s c -l extension_configs -d 'Read extension configurations from CONFIG_FILE'
complete -c markdown_py -s q -l quiet -d 'Suppress all warnings'
complete -c markdown_py -s v -l verbose -d 'Print all warnings'
complete -c markdown_py -l noisy -d 'Print debug messages'

