# mass-bug
# Autogenerated from man page /usr/share/man/man1/mass-bug.1.gz
complete -c mass-bug -l severity -d 'Specify the severity with which bugs should be filed.  Default is normal'
complete -c mass-bug -l display -d 'Fill out the templates for each package and display them all for verification'
complete -c mass-bug -l send -d 'Actually send the bug reports. ie n'
complete -c mass-bug -l subject -d el
complete -c mass-bug -l tags -d 'Set the \\s-1BTS\\s0 pseudo-header for tags'
complete -c mass-bug -l user -d 'Set the \\s-1BTS\\s0 pseudo-header for a usertags\' user'
complete -c mass-bug -l usertags -d 'Set the \\s-1BTS\\s0 pseudo-header for usertags'
complete -c mass-bug -l control -d 'Add a \\s-1BTS\\s0 control command'
complete -c mass-bug -l source -d 'Specify that package names refer to source packages rather than binary packag…'
complete -c mass-bug -l sendmail -d 'Specify the sendmail command'
complete -c mass-bug -l no-wrap -d 'Do not wrap the template to lines of 70 characters'
complete -c mass-bug -l no-conf -l noconf -d 'Do not read any configuration files'
complete -c mass-bug -l help -d 'Provide a usage message'

