# mk-build-deps
# Autogenerated from man page /usr/share/man/man1/mk-build-deps.1.gz
complete -c mk-build-deps -s i -l install -d 'Install the generated packages and its build-dependencies'
complete -c mk-build-deps -s t -l tool -d 'When installing the generated package use the specified tool'
complete -c mk-build-deps -s r -l remove -d 'Remove the package file after installing it'
complete -c mk-build-deps -s a -l arch -d 'Set the architecture of the produced binary package to foo'
complete -c mk-build-deps -l host-arch -d 'Set the host architecture the binary package is built for'
complete -c mk-build-deps -l build-arch -d 'Set the build architecture the binary package is built for'
complete -c mk-build-deps -s B -l build-dep -d 'Generate a package which only depends on the source package\'s Build-Depends d…'
complete -c mk-build-deps -s A -l build-indep -d 'Generate a package which only depends on the source package\'s Build-Depends-I…'
complete -c mk-build-deps -s P -l build-profiles -d 'Generate a package which only depends on build dependencies with the build pr…'
complete -c mk-build-deps -s h -l help -d 'Show a summary of options'
complete -c mk-build-deps -s v -l version -d 'Show version and copyright information'

