# mount.zfs
# Autogenerated from man page /usr/share/man/man8/mount.zfs.8.gz
complete -c 'mount.zfs' -s s -d 'Ignore unknown (sloppy) mount options'
complete -c 'mount.zfs' -s f -d 'Do everything except actually executing the system call'
complete -c 'mount.zfs' -s n -d 'Never update /etc/mtab'
complete -c 'mount.zfs' -s v -d 'Print resolved mount options and parser state'
complete -c 'mount.zfs' -s h -d 'Print the usage message'
complete -c 'mount.zfs' -s o -d 'This private flag indicates that mount 8 is being called by the zfs 8 command'

