# mpath.1p
# Autogenerated from man page /usr/share/man/man1/mpath.1p.gz
complete -c 'mpath.1p' -s h -s '?' -l help -d 'Print this help message and exit'
complete -c 'mpath.1p' -s f -l full -d 'Print module name'

