# nala-list
# Autogenerated from man page /usr/share/man/man8/nala-list.8.gz
complete -c nala-list -l full -d 'Print the full description of each package'
complete -c nala-list -s i -l installed -d 'List only packages that are installed'
complete -c nala-list -s N -l nala-installed -d 'List only packages explicitly installed with nala'
complete -c nala-list -s u -l upgradable -d 'List only packages that are upgradable'
complete -c nala-list -s a -l all-versions -d 'Show all versions of a package'
complete -c nala-list -s V -l virtual -d 'List only virtual packages'
complete -c nala-list -l debug -d 'Print helpful information for solving issues'
complete -c nala-list -s v -l verbose -d 'Disable scrolling text and print extra information'
complete -c nala-list -s h -l help -d 'Shows this man page.  COPYRIGHT'

