# nala-history
# Autogenerated from man page /usr/share/man/man8/nala-history.8.gz
complete -c nala-history -l installed -d 'Show only packages that were explicitly installed with Nala. RS '
complete -c nala-history -l debug -d 'Print helpful information for solving issues'
complete -c nala-history -s v -l verbose -d 'Disable scrolling text and print extra information'
complete -c nala-history -s h -l help -d 'Shows this man page.  COPYRIGHT'

