# nala-update
# Autogenerated from man page /usr/share/man/man8/nala-update.8.gz
complete -c nala-update -l debug -d 'Print helpful information for solving issues'
complete -c nala-update -l raw-dpkg -d 'Force nala not to format dpkg output'
complete -c nala-update -s o -l option -d 'Set options to pass through to apt, nala, or dpkg'
complete -c nala-update -s v -l verbose -d 'Disable scrolling text and print extra information'
complete -c nala-update -s h -l help -d 'Shows this man page.  COPYRIGHT'

