# nala-show
# Autogenerated from man page /usr/share/man/man8/nala-show.8.gz
complete -c nala-show -s a -l all-versions -d 'Show all versions of a package'
complete -c nala-show -l debug -d 'Print helpful information for solving issues'
complete -c nala-show -s v -l verbose -d 'Disable scrolling text and print extra information'
complete -c nala-show -s h -l help -d 'Shows this man page.  COPYRIGHT'

