# nala-search
# Autogenerated from man page /usr/share/man/man8/nala-search.8.gz
complete -c nala-search -l full -d 'Print the full description of each package'
complete -c nala-search -s n -l names -d 'Search only package names'
complete -c nala-search -s i -l installed -d 'List only packages that are installed'
complete -c nala-search -s N -l nala-installed -d 'List only packages explicitly installed with nala'
complete -c nala-search -s u -l upgradable -d 'List only packages that are upgradable'
complete -c nala-search -s a -l all-versions -d 'Show all versions of a package'
complete -c nala-search -s A -l all-arches -d 'Show all architectures of a package'
complete -c nala-search -s V -l virtual -d 'List only virtual packages'
complete -c nala-search -l debug -d 'Print helpful information for solving issues'
complete -c nala-search -s v -l verbose -d 'Disable scrolling text and print extra information'
complete -c nala-search -s h -l help -d 'Shows this man page.  COPYRIGHT'

