# nala-clean
# Autogenerated from man page /usr/share/man/man8/nala-clean.8.gz
complete -c nala-clean -l lists -d 'Additionally clean out the package lists normally found in /var/lib/apt/lists…'
complete -c nala-clean -l fetch -d 'This will remove the nala-sources. list file created from nala fetch'
complete -c nala-clean -l debug -d 'Print helpful information for solving issues'
complete -c nala-clean -s v -l verbose -d 'Disable scrolling text and print extra information'
complete -c nala-clean -s h -l help -d 'Shows this man page.  COPYRIGHT'

