# nala-upgrade
# Autogenerated from man page /usr/share/man/man8/nala-upgrade.8.gz
complete -c nala-upgrade -l exclude -d 'Specify packages to exclude during upgrade.  Accepts globs*'
complete -c nala-upgrade -l full -l no-full
complete -c nala-upgrade -l purge -d 'Purge any packages that would removed during the transaction'
complete -c nala-upgrade -l debug -d 'Print helpful information for solving issues'
complete -c nala-upgrade -l raw-dpkg -d 'Force nala not to format dpkg output'
complete -c nala-upgrade -s d -l download-only -d 'Packages are only retrieved, not unpacked or installed'
complete -c nala-upgrade -l remove-essential -d 'Allow the removal of essential packages'
complete -c nala-upgrade -l assume-yes -l assume-no
complete -c nala-upgrade -s y -d 'Automatically select yes for any prompts which may need your input'
complete -c nala-upgrade -s n -d 'Automatically select no for any prompts which may need your input'
complete -c nala-upgrade -s o -l option -d 'Set options to pass through to apt, nala, or dpkg'
complete -c nala-upgrade -s v -l verbose -d 'Disable scrolling text and print extra information'
complete -c nala-upgrade -s h -l help -d 'Shows this man page'
complete -c nala-upgrade -l autoremove -l no-autoremove
complete -c nala-upgrade -l update -l no-update
complete -c nala-upgrade -l install-recommends -l no-install-recommends
complete -c nala-upgrade -l fix-broken -l no-fix-broken

