# nala-install
# Autogenerated from man page /usr/share/man/man8/nala-install.8.gz
complete -c nala-install -l purge -d 'Purge any packages that would removed during the transaction'
complete -c nala-install -l debug -d 'Print helpful information for solving issues'
complete -c nala-install -l raw-dpkg -d 'Force nala not to format dpkg output'
complete -c nala-install -s d -l download-only -d 'Packages are only retrieved, not unpacked or installed'
complete -c nala-install -l remove-essential -d 'Allow the removal of essential packages'
complete -c nala-install -l assume-yes -l assume-no
complete -c nala-install -s y -d 'Automatically select yes for any prompts which may need your input'
complete -c nala-install -s n -d 'Automatically select no for any prompts which may need your input'
complete -c nala-install -s o -l option -d 'Set options to pass through to apt, nala, or dpkg'
complete -c nala-install -s v -l verbose -d 'Disable scrolling text and print extra information'
complete -c nala-install -s h -l help -d 'Shows this man page'
complete -c nala-install -l autoremove -l no-autoremove
complete -c nala-install -l update -l no-update
complete -c nala-install -l install-recommends -l no-install-recommends
complete -c nala-install -l fix-broken -l no-fix-broken

