# nala-fetch
# Autogenerated from man page /usr/share/man/man8/nala-fetch.8.gz
complete -c nala-fetch -l debian -d 'Instead of auto detecting the distro and release, you can use this switch to …'
complete -c nala-fetch -l ubuntu -d 'Much like --debian but for Ubuntu nala fetch --ubuntu jammy'
complete -c nala-fetch -l devuan -d 'Much like --debian but for Devuan nala fetch --devuan unstable'
complete -c nala-fetch -l https-only -d 'fetch will only provide https mirrors'
complete -c nala-fetch -l auto -d 'Run fetch uninteractively'
complete -c nala-fetch -l fetches -d 'This controls the number of mirrors to fetch'
complete -c nala-fetch -l sources -d 'Add the source repos for the mirror, if it exists'
complete -c nala-fetch -l non-free -d 'Add contrib and non-free components of the Debian mirrors'
complete -c nala-fetch -l debug -d 'Print helpful information for solving issues'
complete -c nala-fetch -s c -l country -d 'Specify your country to limit the mirror search using the 2 letter ISO countr…'
complete -c nala-fetch -s v -l verbose -d 'Disable scrolling text and print extra information'
complete -c nala-fetch -s h -l help -d 'Shows this man page.  COPYRIGHT'

