# nala-autoremove
# Autogenerated from man page /usr/share/man/man8/nala-autoremove.8.gz
complete -c nala-autoremove -l purge -d OPTIONS
complete -c nala-autoremove -l config -d 'Purge configuration files for packages that are no longer installed'
complete -c nala-autoremove -l debug -d 'Print helpful information for solving issues'
complete -c nala-autoremove -l raw-dpkg -d 'Force nala not to format dpkg output'
complete -c nala-autoremove -s d -l download-only -d 'Packages are only retrieved, not unpacked or installed'
complete -c nala-autoremove -l remove-essential -d 'Allow the removal of essential packages'
complete -c nala-autoremove -l assume-yes -l assume-no
complete -c nala-autoremove -s y -d 'Automatically select yes for any prompts which may need your input'
complete -c nala-autoremove -s n -d 'Automatically select no for any prompts which may need your input'
complete -c nala-autoremove -s o -l option -d 'Set options to pass through to apt, nala, or dpkg'
complete -c nala-autoremove -s v -l verbose -d 'Disable scrolling text and print extra information'
complete -c nala-autoremove -s h -l help -d 'Shows this man page'
complete -c nala-autoremove -l update -l no-update
complete -c nala-autoremove -l fix-broken -l no-fix-broken

