# nala-remove
# Autogenerated from man page /usr/share/man/man8/nala-remove.8.gz
complete -c nala-remove -l purge
complete -c nala-remove -l debug -d 'Print helpful information for solving issues'
complete -c nala-remove -l raw-dpkg -d 'Force nala not to format dpkg output'
complete -c nala-remove -s d -l download-only -d 'Packages are only retrieved, not unpacked or installed'
complete -c nala-remove -l remove-essential -d 'Allow the removal of essential packages'
complete -c nala-remove -l assume-yes -l assume-no
complete -c nala-remove -s y -d 'Automatically select yes for any prompts which may need your input'
complete -c nala-remove -s n -d 'Automatically select no for any prompts which may need your input'
complete -c nala-remove -s o -l option -d 'Set options to pass through to apt, nala, or dpkg'
complete -c nala-remove -s v -l verbose -d 'Disable scrolling text and print extra information'
complete -c nala-remove -s h -l help -d 'Shows this man page'
complete -c nala-remove -l autoremove -l no-autoremove
complete -c nala-remove -l update -l no-update
complete -c nala-remove -l install-recommends -l no-install-recommends
complete -c nala-remove -l fix-broken -l no-fix-broken

