# npm2deb
# Autogenerated from man page /usr/share/man/man1/npm2deb.1.gz
complete -c npm2deb -s h -l help -d 'show this help message and exit'
complete -c npm2deb -s D -l debug -d 'set debug level'
complete -c npm2deb -s v -l version -d 'show program\'s version number and exit . SS "commands:"'

