# ntpd
# Autogenerated from man page /usr/share/man/man8/ntpd.8.gz
complete -c ntpd -s 4 -l ipv4
complete -c ntpd -s 6 -l ipv6
complete -c ntpd -s a -l assert
complete -c ntpd -s c -l configfile
complete -c ntpd -s d -l debug-level
complete -c ntpd -s D -l set-debug-level
complete -c ntpd -s f -l driftfile
complete -c ntpd -s g -l panicgate
complete -c ntpd -s G
complete -c ntpd -s h -l help
complete -c ntpd -s i -l jaildir
complete -c ntpd -s I -l interface
complete -c ntpd -s k -l keyfile
complete -c ntpd -s l -l logfile
complete -c ntpd -s L -l novirtualips
complete -c ntpd -s m -l mdns
complete -c ntpd -s n -l nofork
complete -c ntpd -s N -l nice
complete -c ntpd -s p -l pidfile
complete -c ntpd -s P -l priority
complete -c ntpd -s q -l quit
complete -c ntpd -s s -l statsdir
complete -c ntpd -s t -l trustedkey
complete -c ntpd -s u -l user
complete -c ntpd -s U -l updateinterval
complete -c ntpd -s w -l wait-sync
complete -c ntpd -s x -l slew
complete -c ntpd -s z -l var
complete -c ntpd -s Z -l dvar
complete -c ntpd -s V -l version

