# ntpleapfetch
# Autogenerated from man page /usr/share/man/man8/ntpleapfetch.8.gz
complete -c ntpleapfetch -s c -d 'functions, e. g.  to copy the file to other local systems'
complete -c ntpleapfetch -s 4
complete -c ntpleapfetch -s 6
complete -c ntpleapfetch -s e
complete -c ntpleapfetch -s f
complete -c ntpleapfetch -s F
complete -c ntpleapfetch -s i
complete -c ntpleapfetch -s h
complete -c ntpleapfetch -s l
complete -c ntpleapfetch -s L
complete -c ntpleapfetch -s p
complete -c ntpleapfetch -s P
complete -c ntpleapfetch -s q
complete -c ntpleapfetch -s r
complete -c ntpleapfetch -s s
complete -c ntpleapfetch -s t
complete -c ntpleapfetch -s v
complete -c ntpleapfetch -s z
complete -c ntpleapfetch -s Z
complete -c ntpleapfetch -s V -l version

