# ntpmon
# Autogenerated from man page /usr/share/man/man1/ntpmon.1.gz
complete -c ntpmon -s d
complete -c ntpmon -s D
complete -c ntpmon -s h
complete -c ntpmon -s l
complete -c ntpmon -s n
complete -c ntpmon -s s -l srcname
complete -c ntpmon -s S -l srcnumber
complete -c ntpmon -s u
complete -c ntpmon -s V

