# ntpq
# Autogenerated from man page /usr/share/man/man1/ntpq.1.gz
complete -c ntpq -s 4 -l ipv4
complete -c ntpq -s 6 -l ipv6
complete -c ntpq -s a -l authentication
complete -c ntpq -s c -l command
complete -c ntpq -s d -l debug
complete -c ntpq -s D -l set-debug-level
complete -c ntpq -s l -l logfile
complete -c ntpq -s h -l help
complete -c ntpq -s n -l numeric
complete -c ntpq -s s -l srcname
complete -c ntpq -s S -l srcnumber
complete -c ntpq -s p -l peers
complete -c ntpq -s k -l keyfile
complete -c ntpq -s V -l version
complete -c ntpq -s w -l wide
complete -c ntpq -s W -l width
complete -c ntpq -s u -l units

