# ntptrace
# Autogenerated from man page /usr/share/man/man1/ntptrace.1.gz
complete -c ntptrace -s n -l numeric
complete -c ntptrace -s m -l max-hosts
complete -c ntptrace -s r -l host
complete -c ntptrace -s V -l version

