# ntptime
# Autogenerated from man page /usr/share/man/man8/ntptime.8.gz
complete -c ntptime -s c
complete -c ntptime -s e
complete -c ntptime -s f
complete -c ntptime -s h
complete -c ntptime -s j
complete -c ntptime -s m
complete -c ntptime -s o
complete -c ntptime -s r
complete -c ntptime -s s
complete -c ntptime -s t
complete -c ntptime -s V

