# ntpwait
# Autogenerated from man page /usr/share/man/man8/ntpwait.8.gz
complete -c ntpwait -s g
complete -c ntpwait -s n -l tries
complete -c ntpwait -s s -l sleep
complete -c ntpwait -s v -l verbose
complete -c ntpwait -s V -l version

