# obconf
# Autogenerated from man page /usr/share/man/man1/obconf.1.gz
complete -c obconf -l archive -d 'Create a theme archive from the given theme directory'
complete -c obconf -l config-file -d 'Specify the path to the configuration file to use'
complete -c obconf -l install -d 'Installs the given theme archive and selects it'
complete -c obconf -l tab -d 'Display the tab number NUMBER'
complete -c obconf -l version -d 'Displays information about the currently installed version and exists'

