# ocamlrun
# Autogenerated from man page /usr/share/man/man1/ocamlrun.1.gz
complete -c ocamlrun -s b -d 'When the program aborts due to an uncaught exception, print a detailed "back …'
complete -c ocamlrun -s I -d 'Search the directory  dir for dynamically-loaded libraries, in addition to th…'
complete -c ocamlrun -s p -d 'Print the names of the primitives known to this version of  ocamlrun (1) and …'
complete -c ocamlrun -s v -d 'Direct the memory manager to print verbose messages on standard error'
complete -c ocamlrun -o version -d 'Print version string and exit'
complete -c ocamlrun -s g -d 'option to ocamlc (1) set'
complete -c ocamlrun -o vnum -d 'Print short version number and exit'

