# ocamllex
# Autogenerated from man page /usr/share/man/man1/ocamllex.1.gz
complete -c ocamllex -o ml -d 'Output code that does not use OCaml\'s built-in automata interpreter'
complete -c ocamllex -s o -d 'Specify the name of the output file produced by  ocamllex (1)'
complete -c ocamllex -s q -d 'Quiet mode'
complete -c ocamllex -s v -o version -d 'Print version string and exit'
complete -c ocamllex -o vnum -d 'Print short version number and exit'
complete -c ocamllex -o help -l help -d 'Display a short usage summary and exit'

