# ocamlprof
# Autogenerated from man page /usr/share/man/man1/ocamlprof.1.gz
complete -c ocamlprof -s f -d 'Specifies an alternate dump file of profiling information'
complete -c ocamlprof -s F -d 'Specifies an additional string to be output with profiling information'
complete -c ocamlprof -o impl -d 'Compile the file  filename as an implementation file, even if its extension i…'
complete -c ocamlprof -o intf -d 'Compile the file  filename as an interface file, even if its extension is not '
complete -c ocamlprof -o version -d 'Print version string and exit'
complete -c ocamlprof -o vnum -d 'Print short version number and exit'
complete -c ocamlprof -o help -l help -d 'Display a short usage summary and exit'

