# ocamloptp
# Autogenerated from man page /usr/share/man/man1/ocamloptp.1.gz
complete -c ocamloptp -o pp -d 'option is not supported'
complete -c ocamloptp -s P -d 'option.  The letters indicate which parts of the program should be profiled:'
complete -c ocamloptp -s p -d 'with the same argument and meaning as'

