# ocamlyacc
# Autogenerated from man page /usr/share/man/man1/ocamlyacc.1.gz
complete -c ocamlyacc -s b -d 'Name the output files R prefix . ml, R prefix . mli, R prefix '
complete -c ocamlyacc -s q -d 'This option has no effect'
complete -c ocamlyacc -l strict -d 'Reject grammars with conflicts'
complete -c ocamlyacc -s v -d 'Generate a description of the parsing tables and a report on conflicts result…'
complete -c ocamlyacc -o version -d 'Print version string and exit'
complete -c ocamlyacc -o vnum -d 'Print short version number and exit'

