# ocamlcp
# Autogenerated from man page /usr/share/man/man1/ocamlcp.1.gz
complete -c ocamlcp -o pp -d 'option is not supported'
complete -c ocamlcp -s P -d 'option.  The letters indicate which parts of the program should be profiled:'
complete -c ocamlcp -s p -d 'with the same argument and meaning as'

