# ocamldebug
# Autogenerated from man page /usr/share/man/man1/ocamldebug.1.gz
complete -c ocamldebug -s c -d 'Set the maximum number of simultaneously live checkpoints to R count '
complete -c ocamldebug -o cd -d 'Run the debugger program from the working directory R dir , instead of the cu…'
complete -c ocamldebug -o emacs -d 'Tell the debugger it is executed under Emacs'
complete -c ocamldebug -s I -d 'Add  directory to the list of directories searched for source files and compi…'
complete -c ocamldebug -o machine-readable -d 'Print information in a format more suitable for machines instead of human ope…'
complete -c ocamldebug -s s -d 'Use  socket for communicating with the debugged program'
complete -c ocamldebug -o version -d 'Print version string and exit'
complete -c ocamldebug -o vnum -d 'Print short version number and exit'
complete -c ocamldebug -s g -d 'option: all . cmo and '
complete -c ocamldebug -o help -l help -d 'Display a short usage summary and exit'

