# ocamlmktop
# Autogenerated from man page /usr/share/man/man1/ocamlmktop.1.gz
complete -c ocamlmktop -s v -d 'Print the version string of the compiler and exit'
complete -c ocamlmktop -o vnum -o version -d 'Print the version number of the compiler in short form and exit'
complete -c ocamlmktop -o cclib-l -d 'Pass the  -l libname option to the C linker when linking in ``custom runtime\'…'
complete -c ocamlmktop -o ccopt -d 'Pass the given option to the C compiler and linker, when linking in ``custom …'
complete -c ocamlmktop -o custom -d 'Link in ``custom runtime\'\' mode'
complete -c ocamlmktop -s I -d 'Add the given directory to the list of directories searched for compiled inte…'
complete -c ocamlmktop -o cclib -s l -d 'Pass the'
complete -c ocamlmktop -s o -d 'Specify the name of the toplevel file produced by the linker'

