# openipmigui
# Autogenerated from man page /usr/share/man/man1/openipmigui.1.gz
complete -c openipmigui -l dmsg -d 'Turn on message debugging, this will dump all messages to debug log output'
complete -c openipmigui -l drawmsg -d 'Turn on raw message debugging, this will dump all low-level messages to debug…'
complete -c openipmigui -l dmem -d 'Turn on memory debugging, this will cause memory allocation and deallocations…'
complete -c openipmigui -l logstderr -d 'Send all logs to standard error output as well as the GUI console'
complete -c openipmigui -l trace -d 'Turn on python tracing so that all python procedure calls entered and exited …'
complete -c openipmigui -s n -d 'Turn off reading of the preferences file at startup'
complete -c openipmigui -s p -d 'Use preffile as the name of the preferences file instead of $HOME/'

