# openipmi_eventd
# Autogenerated from man page /usr/share/man/man1/openipmi_eventd.1.gz
complete -c openipmi_eventd -s f -l outfile -d 'Send all events to the given file'
complete -c openipmi_eventd -s k -l exec-now -d 'Immediately spawn the given program and send the event information to that pr…'
complete -c openipmi_eventd -s i -l event-stdin -d 'Send the event information to the program\'s standard input instead of the com…'
complete -c openipmi_eventd -s e -l delete-events -d 'Delete events from the SEL (System Event Log) once they have been processed'
complete -c openipmi_eventd -s b -l dont-daemonize -d 'Do not daemonize the program, run it as a foreground process'
complete -c openipmi_eventd -s d -l debug -d 'Debug the program, turn on output, send all logs to stderr, and do not run th…'

