# origtargz
# Autogenerated from man page /usr/share/man/man1/origtargz.1.gz
complete -c origtargz -s p -l path -d 'Add directory to the list of locations to search for an existing tarball'
complete -c origtargz -s u -l unpack -d 'Unpack the downloaded orig tarball to the current directory, replacing everyt…'
complete -c origtargz -s d -l download-only -d 'Alias for --unpack=no'
complete -c origtargz -s t -l tar-only -d 'When using apt-get source, pass --tar-only to it'

