# pacote
# Autogenerated from man page /usr/share/man/man1/pacote.1.gz
complete -c pacote -l long -d 'Print an object from \'resolve\', including integrity and spec'
complete -c pacote -l json -d 'Print result objects as JSON rather than node\'s default'
complete -c pacote -l help -s h -d 'Print this helpful text'

