# perf-buildid-cache
# Autogenerated from man page /usr/share/man/man1/perf-buildid-cache.1.gz
complete -c perf-buildid-cache -s a -l add
complete -c perf-buildid-cache -s f -l force
complete -c perf-buildid-cache -s k -l kcore
complete -c perf-buildid-cache -s r -l remove
complete -c perf-buildid-cache -s p -l purge
complete -c perf-buildid-cache -s P -l purge-all
complete -c perf-buildid-cache -s M -l missing
complete -c perf-buildid-cache -s u -l update
complete -c perf-buildid-cache -s l -l list
complete -c perf-buildid-cache -s v -l verbose
complete -c perf-buildid-cache -l target-ns -d 'Obtain mount namespace information from the target pid'
complete -c perf-buildid-cache -l debuginfod

