# perf-record
# Autogenerated from man page /usr/share/man/man1/perf-record.1.gz
complete -c perf-record -s e -l event
complete -c perf-record -l filter
complete -c perf-record -l exclude-perf
complete -c perf-record -s a -l all-cpus
complete -c perf-record -s p -l pid
complete -c perf-record -s t -l tid
complete -c perf-record -l inherit
complete -c perf-record -s u -l uid
complete -c perf-record -s r -l realtime
complete -c perf-record -l no-buffering
complete -c perf-record -s c -l count
complete -c perf-record -s o -l output
complete -c perf-record -s i -l no-inherit
complete -c perf-record -s F -l freq
complete -c perf-record -l strict-freq
complete -c perf-record -s m -l mmap-pages
complete -c perf-record -l group
complete -c perf-record -s g
complete -c perf-record -l call-graph
complete -c perf-record -l fomit-frame-pointer -d 'call graphs, using "dwarf", if available (perf tools linked to the libunwind …'
complete -c perf-record -s q -l quiet
complete -c perf-record -s v -l verbose
complete -c perf-record -s s -l stat
complete -c perf-record -s d -l data
complete -c perf-record -l phys-data
complete -c perf-record -l data-page-size
complete -c perf-record -l code-page-size
complete -c perf-record -s T -l timestamp
complete -c perf-record -s P -l period
complete -c perf-record -l sample-cpu
complete -c perf-record -s n -l no-samples
complete -c perf-record -s R -l raw-samples
complete -c perf-record -s C -l cpu
complete -c perf-record -s B -l no-buildid
complete -c perf-record -s N -l no-buildid-cache
complete -c perf-record -s G -l cgroup
complete -c perf-record -s b -l branch-any
complete -c perf-record -s j -l branch-filter
complete -c perf-record -l weight
complete -c perf-record -l namespaces
complete -c perf-record -l all-cgroups
complete -c perf-record -l transaction
complete -c perf-record -l per-thread
complete -c perf-record -s D -l delay
complete -c perf-record -s I -l intr-regs
complete -c perf-record -l user-regs
complete -c perf-record -l running-time
complete -c perf-record -s k -l clockid
complete -c perf-record -s S -l snapshot
complete -c perf-record -l aux-sample
complete -c perf-record -l proc-map-timeout
complete -c perf-record -l switch-events
complete -c perf-record -l clang-path
complete -c perf-record -l clang-opt
complete -c perf-record -l vmlinux
complete -c perf-record -l buildid-all
complete -c perf-record -l buildid-mmap
complete -c perf-record -l aio
complete -c perf-record -l affinity
complete -c perf-record -l mmap-flush
complete -c perf-record -s z -l compression-level
complete -c perf-record -l all-kernel
complete -c perf-record -l all-user
complete -c perf-record -l kernel-callchains
complete -c perf-record -l user-callchains
complete -c perf-record -l timestamp-filename -d 'Append timestamp to output file name'
complete -c perf-record -l timestamp-boundary
complete -c perf-record -l switch-output
complete -c perf-record -l no-no-buildid -l no-no-buildid-cache
complete -c perf-record -l switch-output-event
complete -c perf-record -l switch-max-files
complete -c perf-record -l dry-run
complete -c perf-record -l synth
complete -c perf-record -l tail-synthesize
complete -c perf-record -l overwrite
complete -c perf-record -l kcore
complete -c perf-record -l max-size
complete -c perf-record -l num-thread-synthesize
complete -c perf-record -l control -l control
complete -c perf-record -l threads
complete -c perf-record -l ---------------------------------------------------------- -d 'perf_event_attr:   size                             120   config             …'
complete -c perf-record -l debuginfod
complete -c perf-record -l off-cpu

