# perf-kmem
# Autogenerated from man page /usr/share/man/man1/perf-kmem.1.gz
complete -c perf-kmem -s i -l input
complete -c perf-kmem -s f -l force
complete -c perf-kmem -s v -l verbose
complete -c perf-kmem -l caller
complete -c perf-kmem -l alloc
complete -c perf-kmem -s s -l sort
complete -c perf-kmem -s l -l line
complete -c perf-kmem -l raw-ip
complete -c perf-kmem -l slab
complete -c perf-kmem -l page
complete -c perf-kmem -l live
complete -c perf-kmem -l time

