# perf-buildid-list
# Autogenerated from man page /usr/share/man/man1/perf-buildid-list.1.gz
complete -c perf-buildid-list -s H -l with-hits
complete -c perf-buildid-list -s i -l input
complete -c perf-buildid-list -s f -l force
complete -c perf-buildid-list -s k -l kernel
complete -c perf-buildid-list -s v -l verbose

