# perf-daemon
# Autogenerated from man page /usr/share/man/man1/perf-daemon.1.gz
complete -c perf-daemon -s v -l verbose
complete -c perf-daemon -l config
complete -c perf-daemon -l base
complete -c perf-daemon -s f -l foreground
complete -c perf-daemon -l session

