# perf-trace
# Autogenerated from man page /usr/share/man/man1/perf-trace.1.gz
complete -c perf-trace -s a -l all-cpus
complete -c perf-trace -s e -l expr -l event
complete -c perf-trace -l filter
complete -c perf-trace -s D -l delay
complete -c perf-trace -s o -l output
complete -c perf-trace -s p -l pid
complete -c perf-trace -s t -l tid
complete -c perf-trace -s u -l uid
complete -c perf-trace -s G -l cgroup
complete -c perf-trace -l filter-pids
complete -c perf-trace -s v -l verbose
complete -c perf-trace -l no-inherit
complete -c perf-trace -s m -l mmap-pages
complete -c perf-trace -s C -l cpu
complete -c perf-trace -l duration
complete -c perf-trace -l sched
complete -c perf-trace -l failure
complete -c perf-trace -s i -l input
complete -c perf-trace -s T -l time
complete -c perf-trace -l comm
complete -c perf-trace -s s -l summary
complete -c perf-trace -s S -l with-summary
complete -c perf-trace -l errno-summary
complete -c perf-trace -l tool_stats
complete -c perf-trace -s f -l force
complete -c perf-trace -s F -l pf
complete -c perf-trace -l syscalls
complete -c perf-trace -l no-syscalls
complete -c perf-trace -l call-graph
complete -c perf-trace -l kernel-syscall-graph
complete -c perf-trace -l max-events
complete -c perf-trace -l switch-on
complete -c perf-trace -l switch-off
complete -c perf-trace -l show-on-off-events
complete -c perf-trace -l max-stack
complete -c perf-trace -l min-stack
complete -c perf-trace -l print-sample
complete -c perf-trace -l proc-map-timeout
complete -c perf-trace -l sort-events
complete -c perf-trace -l libtraceevent_print
complete -c perf-trace -l map-dump

