# perf-lock
# Autogenerated from man page /usr/share/man/man1/perf-lock.1.gz
complete -c perf-lock -s i -l input
complete -c perf-lock -s v -l verbose
complete -c perf-lock -s D -l dump-raw-trace
complete -c perf-lock -s f -l force
complete -c perf-lock -s k -l key
complete -c perf-lock -s F -l field
complete -c perf-lock -s c -l combine-locks
complete -c perf-lock -s t -l threads
complete -c perf-lock -s m -l map

