# perf-annotate
# Autogenerated from man page /usr/share/man/man1/perf-annotate.1.gz
complete -c perf-annotate -s i -l input
complete -c perf-annotate -s d -l dsos
complete -c perf-annotate -s s -l symbol
complete -c perf-annotate -s f -l force
complete -c perf-annotate -s v -l verbose
complete -c perf-annotate -s q -l quiet
complete -c perf-annotate -s n -l show-nr-samples
complete -c perf-annotate -s D -l dump-raw-trace
complete -c perf-annotate -s k -l vmlinux
complete -c perf-annotate -l ignore-vmlinux
complete -c perf-annotate -l itrace
complete -c perf-annotate -s m -l modules
complete -c perf-annotate -s l -l print-line
complete -c perf-annotate -s P -l full-paths
complete -c perf-annotate -l stdio
complete -c perf-annotate -l stdio2
complete -c perf-annotate -l stdio-color
complete -c perf-annotate -l tui
complete -c perf-annotate -l gtk
complete -c perf-annotate -s C -l cpu
complete -c perf-annotate -l asm-raw
complete -c perf-annotate -l show-total-period
complete -c perf-annotate -l source
complete -c perf-annotate -l symfs
complete -c perf-annotate -s M -l disassembler-style
complete -c perf-annotate -l objdump
complete -c perf-annotate -l prefix -l prefix-strip
complete -c perf-annotate -l skip-missing
complete -c perf-annotate -l group
complete -c perf-annotate -l demangle
complete -c perf-annotate -l demangle-kernel
complete -c perf-annotate -l percent-type
complete -c perf-annotate -l percent-limit

