# perf-top
# Autogenerated from man page /usr/share/man/man1/perf-top.1.gz
complete -c perf-top -s a -l all-cpus
complete -c perf-top -s c -l count
complete -c perf-top -s C -l cpu
complete -c perf-top -s d -l delay
complete -c perf-top -s e -l event
complete -c perf-top -s E -l entries
complete -c perf-top -s f -l count-filter
complete -c perf-top -l group
complete -c perf-top -l group-sort-idx
complete -c perf-top -s F -l freq
complete -c perf-top -s i -l inherit
complete -c perf-top -s k -l vmlinux
complete -c perf-top -l ignore-vmlinux
complete -c perf-top -l kallsyms
complete -c perf-top -s m -l mmap-pages
complete -c perf-top -s p -l pid
complete -c perf-top -s t -l tid
complete -c perf-top -s u -l uid
complete -c perf-top -s r -l realtime
complete -c perf-top -l sym-annotate
complete -c perf-top -s K -l hide_kernel_symbols
complete -c perf-top -s U -l hide_user_symbols
complete -c perf-top -l demangle-kernel
complete -c perf-top -s D -l dump-symtab
complete -c perf-top -s v -l verbose
complete -c perf-top -s z -l zero
complete -c perf-top -s s -l sort
complete -c perf-top -l fields
complete -c perf-top -s n -l show-nr-samples
complete -c perf-top -l show-total-period
complete -c perf-top -l dsos
complete -c perf-top -l comms
complete -c perf-top -l symbols
complete -c perf-top -s M -l disassembler-style
complete -c perf-top -l prefix -l prefix-strip
complete -c perf-top -l source
complete -c perf-top -l asm-raw
complete -c perf-top -s g
complete -c perf-top -l call-graph
complete -c perf-top -l children
complete -c perf-top -l max-stack
complete -c perf-top -l ignore-callees
complete -c perf-top -l percent-limit
complete -c perf-top -l percentage
complete -c perf-top -s w -l column-widths
complete -c perf-top -l proc-map-timeout
complete -c perf-top -s b -l branch-any
complete -c perf-top -s j -l branch-filter
complete -c perf-top -l raw-trace
complete -c perf-top -l hierarchy
complete -c perf-top -l overwrite
complete -c perf-top -l force
complete -c perf-top -l num-thread-synthesize
complete -c perf-top -l namespaces
complete -c perf-top -s G -l cgroup
complete -c perf-top -l all-cgroups
complete -c perf-top -l switch-on
complete -c perf-top -l switch-off
complete -c perf-top -l show-on-off-events
complete -c perf-top -l stitch-lbr

