# perf-config
# Autogenerated from man page /usr/share/man/man1/perf-config.1.gz
complete -c perf-config -s l -l list
complete -c perf-config -l user
complete -c perf-config -l system
complete -c perf-config -o g/--call-graph -d 'call-graph. record-mode'
complete -c perf-config -l slab -l page -d 'record. *, record. build-id'
complete -c perf-config -s F -d 'function_graph.  llvm. *, llvm. clang-path'

