# perf-diff
# Autogenerated from man page /usr/share/man/man1/perf-diff.1.gz
complete -c perf-diff -s D -l dump-raw-trace
complete -c perf-diff -l kallsyms
complete -c perf-diff -s m -l modules
complete -c perf-diff -s d -l dsos
complete -c perf-diff -s C -l comms
complete -c perf-diff -s S -l symbols
complete -c perf-diff -s s -l sort
complete -c perf-diff -s t -l field-separator
complete -c perf-diff -s v -l verbose
complete -c perf-diff -s q -l quiet
complete -c perf-diff -s f -l force
complete -c perf-diff -l symfs
complete -c perf-diff -s b -l baseline-only
complete -c perf-diff -s c -l compute
complete -c perf-diff -l cycles-hist
complete -c perf-diff -s p -l period
complete -c perf-diff -s F -l formula
complete -c perf-diff -s o -l order
complete -c perf-diff -l percentage
complete -c perf-diff -l time
complete -c perf-diff -l cpu
complete -c perf-diff -l pid
complete -c perf-diff -l tid
complete -c perf-diff -l stream
complete -c perf-diff -l ------------------------------------- -d 'b                    x          f1 b          x         x          f2 b      …'

