# perf-list
# Autogenerated from man page /usr/share/man/man1/perf-list.1.gz
complete -c perf-list -s d -l desc
complete -c perf-list -l no-desc
complete -c perf-list -s v -l long-desc
complete -c perf-list -l debug
complete -c perf-list -l details
complete -c perf-list -l deprecated
complete -c perf-list -l cputype
complete -c perf-list -l raw-dump -d ' 2. c'

