# perf-probe
# Autogenerated from man page /usr/share/man/man1/perf-probe.1.gz
complete -c perf-probe -s k -l vmlinux
complete -c perf-probe -s m -l module
complete -c perf-probe -s s -l source
complete -c perf-probe -s v -l verbose
complete -c perf-probe -s q -l quiet
complete -c perf-probe -s a -l add
complete -c perf-probe -s d -l del
complete -c perf-probe -s l -l list
complete -c perf-probe -s L -l line
complete -c perf-probe -s V -l vars
complete -c perf-probe -l externs
complete -c perf-probe -l no-inlines
complete -c perf-probe -s F -l funcs
complete -c perf-probe -s D -l definition
complete -c perf-probe -l filter
complete -c perf-probe -s f -l force
complete -c perf-probe -s n -l dry-run
complete -c perf-probe -l cache
complete -c perf-probe -l max-probes
complete -c perf-probe -l target-ns -d 'Obtain mount namespace information from the target pid'
complete -c perf-probe -s x -l exec
complete -c perf-probe -l demangle
complete -c perf-probe -l demangle-kernel

