# perf-script-perl
# Autogenerated from man page /usr/share/man/man1/perf-script-perl.1.gz
complete -c perf-script-perl -s g -d 'That will generate a starter script containing a handler for each of the even…'

