# perf-kvm
# Autogenerated from man page /usr/share/man/man1/perf-kvm.1.gz
complete -c perf-kvm -s i -l input
complete -c perf-kvm -s o -l output
complete -c perf-kvm -l host
complete -c perf-kvm -l guest
complete -c perf-kvm -l guestmount
complete -c perf-kvm -l guestkallsyms
complete -c perf-kvm -l guestmodules
complete -c perf-kvm -l guestvmlinux
complete -c perf-kvm -l guest-code
complete -c perf-kvm -s v -l verbose
complete -c perf-kvm -l vcpu
complete -c perf-kvm -l event
complete -c perf-kvm -s k -l key
complete -c perf-kvm -s p -l pid
complete -c perf-kvm -s d -l display
complete -c perf-kvm -s m -l mmap-pages
complete -c perf-kvm -s a -l all-cpus
complete -c perf-kvm -l duration
complete -c perf-kvm -l proc-map-timeout

