# perf-evlist
# Autogenerated from man page /usr/share/man/man1/perf-evlist.1.gz
complete -c perf-evlist -s i -l input
complete -c perf-evlist -s f -l force
complete -c perf-evlist -s F -l freq
complete -c perf-evlist -s v -l verbose
complete -c perf-evlist -s g -l group
complete -c perf-evlist -l trace-fields

