# perf-stat
# Autogenerated from man page /usr/share/man/man1/perf-stat.1.gz
complete -c perf-stat -s e -l event
complete -c perf-stat -s i -l no-inherit
complete -c perf-stat -s p -l pid
complete -c perf-stat -s t -l tid
complete -c perf-stat -s b -l bpf-prog
complete -c perf-stat -l bpf-counters
complete -c perf-stat -l bpf-attr-map
complete -c perf-stat -s a -l all-cpus
complete -c perf-stat -l no-scale
complete -c perf-stat -s d -l detailed
complete -c perf-stat -s r -l repeat
complete -c perf-stat -s B -l big-num
complete -c perf-stat -s C -l cpu
complete -c perf-stat -s A -l no-aggr
complete -c perf-stat -s n -l null
complete -c perf-stat -s v -l verbose
complete -c perf-stat -s x -l field-separator
complete -c perf-stat -l table
complete -c perf-stat -s G -l cgroup
complete -c perf-stat -l for-each-cgroup
complete -c perf-stat -s o -l output
complete -c perf-stat -l append
complete -c perf-stat -l log-fd
complete -c perf-stat -l control -l control
complete -c perf-stat -l delay -s 1 -d 'to synchronize with the controlling process'
complete -c perf-stat -l pre -l post
complete -c perf-stat -s I -l interval-print
complete -c perf-stat -l interval-count
complete -c perf-stat -l interval-clear
complete -c perf-stat -l timeout
complete -c perf-stat -l metric-only
complete -c perf-stat -l per-socket
complete -c perf-stat -l per-die
complete -c perf-stat -l per-core
complete -c perf-stat -l per-thread
complete -c perf-stat -l per-node
complete -c perf-stat -s D
complete -c perf-stat -s T -l transaction
complete -c perf-stat -l metric-no-group
complete -c perf-stat -l metric-no-merge
complete -c perf-stat -l quiet
complete -c perf-stat -l input
complete -c perf-stat -s M -l metrics
complete -c perf-stat -l topdown
complete -c perf-stat -l td-level
complete -c perf-stat -l no-merge
complete -c perf-stat -l hybrid-merge
complete -c perf-stat -l smi-cost
complete -c perf-stat -l all-kernel
complete -c perf-stat -l all-user
complete -c perf-stat -l percore-show-thread
complete -c perf-stat -l summary
complete -c perf-stat -l no-csv-summary
complete -c perf-stat -l cputype
complete -c perf-stat -l ---------------------------------------------------------- -d 'perf_event_attr:   size                             120   config             …'

