# perf-inject
# Autogenerated from man page /usr/share/man/man1/perf-inject.1.gz
complete -c perf-inject -s b -l build-ids
complete -c perf-inject -l buildid-all -d 'Inject build-ids of all DSOs into the output stream'
complete -c perf-inject -s v -l verbose
complete -c perf-inject -s i -l input
complete -c perf-inject -s o -l output
complete -c perf-inject -s s -l sched-stat
complete -c perf-inject -s k -l vmlinux
complete -c perf-inject -l ignore-vmlinux
complete -c perf-inject -l kallsyms
complete -c perf-inject -l itrace
complete -c perf-inject -l strip
complete -c perf-inject -s j -l jit
complete -c perf-inject -s f -l force
complete -c perf-inject -l vm-time-correlation

