# perf-report
# Autogenerated from man page /usr/share/man/man1/perf-report.1.gz
complete -c perf-report -s i -l input
complete -c perf-report -s v -l verbose
complete -c perf-report -s q -l quiet
complete -c perf-report -s n -l show-nr-samples
complete -c perf-report -l show-cpu-utilization
complete -c perf-report -s T -l threads
complete -c perf-report -s c -l comms
complete -c perf-report -l pid
complete -c perf-report -l tid
complete -c perf-report -s d -l dsos
complete -c perf-report -s S -l symbols
complete -c perf-report -l symbol-filter
complete -c perf-report -s U -l hide-unresolved
complete -c perf-report -s s -l sort
complete -c perf-report -l time-quantum -d 'oc code_page_size: the code page size of sampled code address (ip) oc ins_lat…'
complete -c perf-report -s F -l fields
complete -c perf-report -s p -l parent
complete -c perf-report -s x -l exclude-other
complete -c perf-report -s w -l column-widths
complete -c perf-report -s t -l field-separator
complete -c perf-report -s D -l dump-raw-trace
complete -c perf-report -l disable-order
complete -c perf-report -s g -l call-graph
complete -c perf-report -l children
complete -c perf-report -l max-stack
complete -c perf-report -s G -l inverted
complete -c perf-report -l ignore-callees
complete -c perf-report -l pretty
complete -c perf-report -l stdio
complete -c perf-report -l stdio-color
complete -c perf-report -l tui
complete -c perf-report -l gtk
complete -c perf-report -s k -l vmlinux
complete -c perf-report -l ignore-vmlinux
complete -c perf-report -l kallsyms
complete -c perf-report -s m -l modules
complete -c perf-report -s f -l force
complete -c perf-report -l symfs
complete -c perf-report -s C -l cpu
complete -c perf-report -s M -l disassembler-style
complete -c perf-report -l source
complete -c perf-report -l asm-raw
complete -c perf-report -l show-total-period
complete -c perf-report -s I -l show-info
complete -c perf-report -s b -l branch-stack
complete -c perf-report -l branch-history
complete -c perf-report -l objdump
complete -c perf-report -l prefix -l prefix-strip
complete -c perf-report -l group
complete -c perf-report -l group-sort-idx
complete -c perf-report -l demangle
complete -c perf-report -l demangle-kernel
complete -c perf-report -l mem-mode
complete -c perf-report -l percent-limit
complete -c perf-report -l percentage
complete -c perf-report -l header
complete -c perf-report -l header-only
complete -c perf-report -l time
complete -c perf-report -l switch-on
complete -c perf-report -l switch-off
complete -c perf-report -l show-on-off-events
complete -c perf-report -l itrace
complete -c perf-report -l full-source-path
complete -c perf-report -l show-ref-call-graph
complete -c perf-report -l stitch-lbr
complete -c perf-report -l socket-filter
complete -c perf-report -l samples
complete -c perf-report -l raw-trace
complete -c perf-report -l hierarchy
complete -c perf-report -l inline
complete -c perf-report -l mmaps
complete -c perf-report -l ns
complete -c perf-report -l stats
complete -c perf-report -l tasks
complete -c perf-report -l percent-type
complete -c perf-report -l total-cycles
complete -c perf-report -l skip-empty

