# perf-intel-pt
# Autogenerated from man page /usr/share/man/man1/perf-intel-pt.1.gz
complete -c perf-intel-pt -l kcore -d 'sudo perf record -o pt_ls --kcore -e intel_pt// -- ls which will create a dir…'
complete -c perf-intel-pt -l insn-trace
complete -c perf-intel-pt -l src-trace -d 'As mentioned above, it is easy to capture too much data'
complete -c perf-intel-pt -s e -d 'will use a default config value.   Currently that is the same as'
complete -c perf-intel-pt -l ---------------------------------------------------------- -d 'perf_event_attr: type                             6 size                     …'
complete -c perf-intel-pt -l aux-sample -d 'Optionally it can be followed by the sample size in bytes e. g'
complete -c perf-intel-pt -s S -d 'Optionally it can be followed by the snapshot size e. g'
complete -c perf-intel-pt -o S0x100000 -d 'The default snapshot size is the auxtrace mmap size'
complete -c perf-intel-pt -s m -d 'selects a buffer size of 16 pages i. e.  64KiB'
complete -c perf-intel-pt -l itrace -d 'which, in turn, is the same as'
complete -c perf-intel-pt -o 'o	Suppress'
complete -c perf-intel-pt -o 'l	Suppress' -d 'For example, for errors but not overflow or data lost errors:'
complete -c perf-intel-pt -o 'a	Suppress' -d '+a	Log all perf events +o	Output to stdout instead of "intel_pt'
complete -c perf-intel-pt -l count
complete -c perf-intel-pt -l no-itrace -d 'PERF REPORT'

