# perf
# Autogenerated from man page /usr/share/man/man1/perf.1.gz
complete -c perf -s h -l help
complete -c perf -s v -l version
complete -c perf -o vv
complete -c perf -l exec-path
complete -c perf -l html-path
complete -c perf -s p -l paginate
complete -c perf -l no-pager
complete -c perf -l buildid-dir
complete -c perf -l list-cmds
complete -c perf -l list-opts
complete -c perf -l debugfs-dir
complete -c perf -l debug

