# perf-script
# Autogenerated from man page /usr/share/man/man1/perf-script.1.gz
complete -c perf-script -s D -l dump-raw-trace
complete -c perf-script -s L -l Latency
complete -c perf-script -s l -l list
complete -c perf-script -s s -l script
complete -c perf-script -s g -l gen-script
complete -c perf-script -l dlfilter
complete -c perf-script -l dlarg
complete -c perf-script -l list-dlfilters
complete -c perf-script -s a
complete -c perf-script -s i -l input
complete -c perf-script -s d -l debug-mode
complete -c perf-script -s F -l fields
complete -c perf-script -o cpu -d 'removes the cpu field and adds the insn field'
complete -c perf-script -o Fsw:-cpu -o period -d 'removes cpu and period from software events'
complete -c perf-script -s k -l vmlinux
complete -c perf-script -l kallsyms
complete -c perf-script -l symfs
complete -c perf-script -s G -l hide-call-graph
complete -c perf-script -l stop-bt
complete -c perf-script -s C -l cpu
complete -c perf-script -s c -l comms
complete -c perf-script -l pid
complete -c perf-script -l tid
complete -c perf-script -s I -l show-info
complete -c perf-script -l show-kernel-path
complete -c perf-script -l show-task-events -d 'Display task related events (e. g.  FORK, COMM, EXIT)'
complete -c perf-script -l show-mmap-events -d 'Display mmap related events (e. g.  MMAP, MMAP2)'
complete -c perf-script -l show-namespace-events -d 'Display namespace events i. e.  events of type PERF_RECORD_NAMESPACES'
complete -c perf-script -l show-switch-events -d 'Display context switch events i. e'
complete -c perf-script -l show-lost-events -d 'Display lost events i. e.  events of type PERF_RECORD_LOST'
complete -c perf-script -l show-round-events -d 'Display finished round events i. e'
complete -c perf-script -l show-bpf-events -d 'Display bpf events i. e'
complete -c perf-script -l show-cgroup-events -d 'Display cgroup events i. e.  events of type PERF_RECORD_CGROUP'
complete -c perf-script -l show-text-poke-events -d 'Display text poke events i. e'
complete -c perf-script -l demangle
complete -c perf-script -l demangle-kernel
complete -c perf-script -l header -d 'Show perf. data header'
complete -c perf-script -l header-only -d 'Show only perf. data header'
complete -c perf-script -l itrace
complete -c perf-script -l full-source-path
complete -c perf-script -l max-stack
complete -c perf-script -l ns
complete -c perf-script -s f -l force
complete -c perf-script -l time
complete -c perf-script -l max-blocks
complete -c perf-script -l reltime
complete -c perf-script -l deltatime
complete -c perf-script -l per-event-dump
complete -c perf-script -l inline
complete -c perf-script -l insn-trace
complete -c perf-script -l xed
complete -c perf-script -s S -l symbols
complete -c perf-script -l addr-range
complete -c perf-script -l dsos
complete -c perf-script -l call-trace
complete -c perf-script -l call-ret-trace
complete -c perf-script -l graph-function
complete -c perf-script -l switch-on
complete -c perf-script -l switch-off
complete -c perf-script -l show-on-off-events
complete -c perf-script -l stitch-lbr
complete -c perf-script -l guest-code

