# plotchangelog
# Autogenerated from man page /usr/share/man/man1/plotchangelog.1.gz
complete -c plotchangelog -s l -l linecount -d 'Instead of using the Debian version number as the Y axis, use the number of l…'
complete -c plotchangelog -s b -l bugcount -d 'Instead of using the Debian version number as the Y axis, use the number of b…'
complete -c plotchangelog -s c -l cumulative -d 'When used together with either  --bugcount or  --linecount , graphs the cumul…'
complete -c plotchangelog -s v -l no-version -d 'Do not show upstream version labels.  Useful if the graph gets too crowded'
complete -c plotchangelog -s m -l no-maint -d 'Do not differentiate between different maintainers of the package'
complete -c plotchangelog -s s -l save -d 'Save the graph to file in PostScript format instead of immediately displaying…'
complete -c plotchangelog -s u -l urgency -d 'Use larger points when displaying higher-urgency package uploads'
complete -c plotchangelog -l verbose -d 'Output the gnuplot script that is fed into gnuplot (for debugging purposes)'
complete -c plotchangelog -o gcommands -l gnuplot -d 'This allows you to insert  gnuplot (1) commands into the gnuplot script that …'
complete -c plotchangelog -l help -d 'Show a usage summary'
complete -c plotchangelog -l version -d 'Display version, author and copyright information'
complete -c plotchangelog -l noconf -l no-conf -d 'Do not read any configuration files (see below)'
complete -c plotchangelog -s g -d 'may be ignored; see the next variable instead'

