# pod2markdown.1p
# Autogenerated from man page /usr/share/man/man1/pod2markdown.1p.gz
complete -c 'pod2markdown.1p' -l html-encode-chars -d 'A list of characters to encode as \\s-1HTML\\s0 entities'
complete -c 'pod2markdown.1p' -l match-encoding -s m -d 'Use the same \\f(CW\\*(C`=encoding\\*(C\' as the input pod for the output file'
complete -c 'pod2markdown.1p' -l output-encoding -s e -d 'Specify the encoding for the output file'

