# pristine-bz2
# Autogenerated from man page /usr/share/man/man1/pristine-bz2.1.gz
complete -c pristine-bz2 -s v -d 'Verbose mode, show each command that is run'
complete -c pristine-bz2 -s d -d 'Debug mode'
complete -c pristine-bz2 -s k -d 'Don\'t clean up the temporary directory on exit'

