# pristine-xz
# Autogenerated from man page /usr/share/man/man1/pristine-xz.1.gz
complete -c pristine-xz -s v -d 'Verbose mode, show each command that is run'
complete -c pristine-xz -s d -d 'Debug mode'
complete -c pristine-xz -s k -d 'Don\'t clean up the temporary directory on exit'

