# pts-subscribe
# Autogenerated from man page /usr/share/man/man1/pts-subscribe.1.gz
complete -c pts-subscribe -l until -s u -d 'When at(1) should cancel the subscription'
complete -c pts-subscribe -l forever -d 'Don\'t cancel the subscription automatically'
complete -c pts-subscribe -l help -s h -d 'Display a help message and exit successfully'
complete -c pts-subscribe -l version -d 'Display version and copyright information and exit successfully'

