# pts-unsubscribe
# Autogenerated from man page /usr/share/man/man1/pts-unsubscribe.1.gz
complete -c pts-unsubscribe -l until -s u -d 'When at(1) should cancel the subscription'
complete -c pts-unsubscribe -l forever -d 'Don\'t cancel the subscription automatically'
complete -c pts-unsubscribe -l help -s h -d 'Display a help message and exit successfully'
complete -c pts-unsubscribe -l version -d 'Display version and copyright information and exit successfully'

