# python-mkdebian
# Autogenerated from man page /usr/share/man/man1/python-mkdebian.1.gz
complete -c python-mkdebian -l force-control -d 'Force control file behaviour'
complete -c python-mkdebian -l force-copyright -d 'Force whole copyright file to be recreated'
complete -c python-mkdebian -l force-rules -d 'Force whole rules file to be recreated'
complete -c python-mkdebian -l changelog -d 'Add changelog entry to debian/changelog (can be specified multiple times)'
complete -c python-mkdebian -l dependency -d 'Add additional debian package dependency (can be specified multiple times)'
complete -c python-mkdebian -l prefix -d 'Ask for installing all your modules in the dedicated PREFIX (default is /usr)'
complete -c python-mkdebian -l version -d 'Show program\'s version number and exit'
complete -c python-mkdebian -s h -l help -d 'Show this help message and exit'

