# raidz_test
# Autogenerated from man page /usr/share/man/man1/raidz_test.1.gz
complete -c raidz_test -s h -d 'Print a help summary'
complete -c raidz_test -s a -d 'Ashift value'
complete -c raidz_test -s o -d 'ZIO offset for each raidz block.  The offset\'s value is 2^zio_off_shift'
complete -c raidz_test -s d -d 'Number of raidz data disks to use.  Additional disks will be used for parity'
complete -c raidz_test -s s -d 'Size of data for raidz block.  The real size is 2^zio_size_shift'
complete -c raidz_test -s r -d 'Set raidz expansion offset'
complete -c raidz_test -s S -d 'Sweep parameter space while verifying the raidz implementations'
complete -c raidz_test -s t -d 'Wall time for sweep test in seconds.  The actual runtime could be longer'
complete -c raidz_test -s B -d 'All implementations are benchmarked using increasing per disk data size'
complete -c raidz_test -s e -d 'Use expanded raidz map allocation function'
complete -c raidz_test -s v -d 'Increase verbosity'
complete -c raidz_test -s T -d 'Debugging option: fail all tests'
complete -c raidz_test -s D -d 'Debugging option: attach gdb 1 when SIGSEGV or SIGABRT are received'

