# rc-alert
# Autogenerated from man page /usr/share/man/man1/rc-alert.1.gz
complete -c rc-alert -l cache -d 'Force the creation of the $XDG_CACHE_HOME/devscripts/rc-alert cache directory'
complete -c rc-alert -l help -s h -d 'Show a summary of options'
complete -c rc-alert -l version -s v -d 'Show version and copyright information'
complete -c rc-alert -l include-tags -s f -d 'A list of tags which the bug must have, in the format used for output'
complete -c rc-alert -l include-tag-op -s t -d 'If set to and, a bug must have all of the tags specified by --include-tags'
complete -c rc-alert -l exclude-tags -d 'A list of tags which the bug must not have, in the same format as --include-t…'
complete -c rc-alert -l exclude-tag-op -d 'If set to and, a bug must have none of the tags specified by --exclude-tags'
complete -c rc-alert -l include-dists -s d -d 'A list of distributions which the bug must apply to, in the format used for o…'
complete -c rc-alert -l include-dist-op -s o -d 'If set to and, a bug must apply to all of the specified distributions in orde…'
complete -c rc-alert -l exclude-dists -d 'A list of distributions to which the bug must not apply, in the same format a…'
complete -c rc-alert -l exclude-dist-op -d 'If set to and, a bug must apply to all of the specified distributions in orde…'
complete -c rc-alert -l debtags -d 'Match packages based on the listed tags'
complete -c rc-alert -l debtags-database -d 'Use a non-standard debtags database'
complete -c rc-alert -l popcon -d 'Sort bugs by the popcon rank of the package the bug belongs to'
complete -c rc-alert -l pc-vote -d 'By default, packages are sorted according to the number of people who have th…'
complete -c rc-alert -l pc-local -d 'Instead of requesting remote data the information from the last popcon run is…'

