# readline-editor
# Autogenerated from man page /usr/share/man/man1/readline-editor.1.gz
complete -c readline-editor -s h -d 'Save the lines typed (history) in file'
complete -c readline-editor -s x -d 'Extend the history file (given in option "-h") if it already exists'
complete -c readline-editor -s t -d 'Display the sequences generated by the keys (for debugging)'
complete -c readline-editor -s v -d 'Print ledit version and exit'
complete -c readline-editor -s l -d 'Tells that length is the maximum line length displayed'
complete -c readline-editor -s a -d 'Ascii encoding: characters whose code is greater than 128 are displayed with …'
complete -c readline-editor -s u -d 'Unicode encoding: the terminal must have been set in unicode mode'

