# reboot
# Autogenerated from man page /usr/share/man/man8/reboot.8.gz
complete -c reboot -s n -d 'Don\'t sync before reboot or halt'
complete -c reboot -s w -d 'Don\'t actually reboot or halt but only write the wtmp record (in the /var/log…'
complete -c reboot -s d -d 'Don\'t write the wtmp record'
complete -c reboot -s f -d 'Force halt or reboot, don\'t call shutdown(8)'
complete -c reboot -s i -d 'Shut down all network interfaces just before halt or reboot'
complete -c reboot -s h -d 'Put all hard drives on the system in stand-by mode just before halt or power-…'
complete -c reboot -s p -d 'When halting the system, switch off the power'

