# reproducible-check
# Autogenerated from man page /usr/share/man/man1/reproducible-check.1.gz
complete -c reproducible-check -s h -l help -d 'show this help message and exit'
complete -c reproducible-check -s d -l debug -d 'show debugging messages'
complete -c reproducible-check -s r -l raw -d 'print unreproducible binary packages only (for dd-list -i)'
complete -c reproducible-check -l version -d 'print version and exit'

