# ri3.0
# Autogenerated from man page /usr/share/man/man1/ri3.0.1.gz
complete -c 'ri3.0' -s i
complete -c 'ri3.0' -s a
complete -c 'ri3.0' -s l
complete -c 'ri3.0' -s T -d 'Synonym for -no-pager.  Pp'
complete -c 'ri3.0' -s w
complete -c 'ri3.0' -l width -d 'Set the width of the output.  Pp'
complete -c 'ri3.0' -l server -d 'Run RDoc server on the given port.  The default port is\\~8214.  Pp'
complete -c 'ri3.0' -s f
complete -c 'ri3.0' -l format -d 'Use the selected formatter'
complete -c 'ri3.0' -s h
complete -c 'ri3.0' -l help -d 'Show help and exit.  Pp'
complete -c 'ri3.0' -s v
complete -c 'ri3.0' -l version -d 'Output version information and exit'
complete -c 'ri3.0' -s d
complete -c 'ri3.0' -l doc-dir -d 'List of directories from which to source documentation in addition to the sta…'
complete -c 'ri3.0' -l no-standard-docs -d 'Do not include documentation from the Ruby standard library, site_lib, instal…'
complete -c 'ri3.0' -l dump -d 'Dump data from an ri cache or data file'

