# rmadison
# Autogenerated from man page /usr/share/man/man1/rmadison.1.gz
complete -c rmadison -s a -l architecture -d 'only show info for \\s-1ARCH\\s0(s)'
complete -c rmadison -s b -l binary-type -d 'only show info for binary \\s-1TYPE\\s0'
complete -c rmadison -s c -l component -d 'only show info for \\s-1COMPONENT\\s0(s)'
complete -c rmadison -s g -l greaterorequal -d 'show buildd \'dep-wait pkg >= {highest version}\' info'
complete -c rmadison -s G -l greaterthan -d 'show buildd \'dep-wait pkg >> {highest version}\' info'
complete -c rmadison -s h -l help -d 'show this help and exit'
complete -c rmadison -s s -l suite -d 'only show info for this suite'
complete -c rmadison -s r -l regex -d 'treat \\s-1PACKAGE\\s0 as a regex '
complete -c rmadison -s S -l source-and-binary -d 'show info for the binary children of source pkgs'
complete -c rmadison -s t -l time -d 'show projectb snapshot and reload time (not supported by all archives)'
complete -c rmadison -s u -l url -d 'use \\s-1URL\\s0 for the query.  Supported shorthands are  debian https://api'
complete -c rmadison -l version -d 'show version and exit'

