# rngtest
# Autogenerated from man page /usr/share/man/man1/rngtest.1.gz
complete -c rngtest -s p -l pipe -d 'Enable pipe mode'
complete -c rngtest -s c -l blockcount -d 'Exit after processing n input blocks, if n is not zero'
complete -c rngtest -s b -l blockstats -d 'Dump statistics every n blocks, if n is not zero'
complete -c rngtest -s t -l timedstats -d 'Dump statistics every n secods, if n is not zero'
complete -c rngtest -s '?' -l help -d 'Give a short summary of all program options'
complete -c rngtest -s V -l version -d 'Print program version'

