# rpmsign
# Autogenerated from man page /usr/share/man/man8/rpmsign.8.gz
complete -c rpmsign -l rpmv3 -d 'Force RPM V3 header+payload signature addition'
complete -c rpmsign -l fskpath -d 'Used with --signfiles, use file signing key Key'
complete -c rpmsign -l certpath -d 'Used with --signverity, use file signing certificate Cert'
complete -c rpmsign -l verityalgo -d 'Used with --signverity, to specify the signing algorithm'
complete -c rpmsign -l signfiles -d 'Sign package files'
complete -c rpmsign -l signverity -d 'Sign package files with fsverity signatures'

