# ruby3.0
# Autogenerated from man page /usr/share/man/man1/ruby3.0.1.gz
complete -c 'ruby3.0' -l copyright -d 'Prints the copyright notice, and quits immediately without running any script'
complete -c 'ruby3.0' -l version -d 'Prints the version of the Ruby interpreter, and quits immediately without run…'
complete -c 'ruby3.0' -s 0 -d '(The digit zero '
complete -c 'ruby3.0' -s C
complete -c 'ruby3.0' -s X -d 'Causes Ruby to switch to the directory.  Pp'
complete -c 'ruby3.0' -s E
complete -c 'ruby3.0' -l encoding -d 'Specifies the default value(s) for external encodings and internal encoding'
complete -c 'ruby3.0' -l external-encoding
complete -c 'ruby3.0' -l internal-encoding -d 'Specify the default external or internal character encoding Pp'
complete -c 'ruby3.0' -s F -d 'Specifies input field separator ( Li "$;" ).  Pp'
complete -c 'ruby3.0' -s I -d 'Used to tell Ruby where to load the library scripts'
complete -c 'ruby3.0' -s K -d 'Specifies KANJI (Japanese) encoding'
complete -c 'ruby3.0' -s S -d 'Makes Ruby use the PATH environment variable to search for script, unless its…'
complete -c 'ruby3.0' -s T -d 'Turns on taint checks at the specified level (default 1).  Pp'
complete -c 'ruby3.0' -s U -d 'Sets the default value for internal encodings ( Li "Encoding'
complete -c 'ruby3.0' -s W -d 'Turns on verbose mode at the specified level without printing the version mes…'
complete -c 'ruby3.0' -s a -d 'Turns on auto-split mode when used with n or p'
complete -c 'ruby3.0' -s c -d 'Causes Ruby to check the syntax of the script and exit without executing'
complete -c 'ruby3.0' -s d
complete -c 'ruby3.0' -l debug -d 'Turns on debug mode.  "$DEBUG" will be set to true.  Pp'
complete -c 'ruby3.0' -s e -d 'Specifies script from command-line while telling Ruby not to search the rest …'
complete -c 'ruby3.0' -s h
complete -c 'ruby3.0' -l help -d 'Prints a summary of the options.  Pp'
complete -c 'ruby3.0' -s i -d 'Specifies in-place-edit mode'
complete -c 'ruby3.0' -s l -d '(The lowercase letter ell '
complete -c 'ruby3.0' -s n -d 'Causes Ruby to assume the following loop around your script, which makes it i…'
complete -c 'ruby3.0' -s p -d 'Acts mostly same as -n switch, but print the value of variable "$_" at the ea…'
complete -c 'ruby3.0' -s r -d 'Causes Ruby to load the library using require'
complete -c 'ruby3.0' -s s -d 'Enables some switch parsing for switches after script name but before any fil…'
complete -c 'ruby3.0' -s v -d 'Enables verbose mode'
complete -c 'ruby3.0' -s w -d 'Enables verbose mode without printing version message at the beginning'
complete -c 'ruby3.0' -s x -d 'Tells Ruby that the script is embedded in a message'
complete -c 'ruby3.0' -s y
complete -c 'ruby3.0' -l yydebug -d 'DO NOT USE.  Pp Turns on compiler debug mode'
complete -c 'ruby3.0' -l disable-
complete -c 'ruby3.0' -l enable- -d 'Disables (or enables) the specified FEATURE'
complete -c 'ruby3.0' -l disable-gems
complete -c 'ruby3.0' -l enable-gems -d 'Disables (or enables) RubyGems libraries'
complete -c 'ruby3.0' -l disable-rubyopt
complete -c 'ruby3.0' -l enable-rubyopt -d 'Ignores (or considers) the RUBYOPT environment variable'
complete -c 'ruby3.0' -l disable-all
complete -c 'ruby3.0' -l enable-all -d 'Disables (or enables) all features.  Pp El Pp'
complete -c 'ruby3.0' -l dump -d 'Dump some information.  Pp Prints the specified target'
complete -c 'ruby3.0' -l verbose -d 'Enables verbose mode without printing version message at the beginning'

