# sadt
# Autogenerated from man page /usr/share/man/man1/sadt.1.gz
complete -c sadt -s v -l verbose -d 'Make the output more verbose'
complete -c sadt -s b -l built-source-tree -d 'Assume that the source tree is already built'
complete -c sadt -l run-autodep8 -l no-run-autodep8 -d 'Control whether to run autodep8\\|(1) to determine the tests to run'
complete -c sadt -l ignore-restriction -d 'Don\'t skip tests that declare the restriction'

