# shcomp93
# Autogenerated from man page /usr/share/man/man1/shcomp93.1.gz
complete -c shcomp93 -s D -l dictionary -d 'Generate a list of strings that need to be placed in a message catalog for in…'
complete -c shcomp93 -s n -l noexec -d 'Displays warning messages for obsolete or non-conforming constructs'
complete -c shcomp93 -s v -l verbose -d 'Displays input from  infile onto standard error as it reads it'
complete -c shcomp93 -l man -d 'Displays this man page on standard error and exits'
complete -c shcomp93 -l help -d 'Shows a short help message and exits.  EXIT STATUS'

