# shell-quote.1p
# Autogenerated from man page /usr/share/man/man1/shell-quote.1p.gz
complete -c 'shell-quote.1p' -l debug -d 'Turn debugging on'
complete -c 'shell-quote.1p' -l help -d 'Show the usage message and die'

