# solterm
# Autogenerated from man page /usr/share/man/man1/solterm.1.gz
complete -c solterm -s e -d 'The character to use to escape, or exit, the program'
complete -c solterm -o notencrypted -d 'Do not encrypt the SOL data going over the connection'
complete -c solterm -o notauthenticated -d 'Do not do integrity checks on the SOL data going over the connection'
complete -c solterm -o bitrate -d 'Set the bitrate to the given value'
complete -c solterm -o alerts -d 'This specifies what to do if a alert that requires a callout occurs on the li…'
complete -c solterm -o holdoff -d 'Specifies that CTS, DTR, and DSR are to be deasserted at the start of the SoL…'
complete -c solterm -s v -d 'Be more verbose.   Maybe specified multiple time for more output'
complete -c solterm -s q -d 'Be less verbose.   Maybe specified multiple time for less output'

