# speedtest
# Autogenerated from man page /usr/share/man/man1/speedtest.1.gz
complete -c speedtest -s h -l help
complete -c speedtest -l no-download
complete -c speedtest -l no-upload
complete -c speedtest -l single
complete -c speedtest -l bytes
complete -c speedtest -l share
complete -c speedtest -l simple
complete -c speedtest -l csv
complete -c speedtest -l csv-delimiter
complete -c speedtest -l csv-header
complete -c speedtest -l json
complete -c speedtest -l list
complete -c speedtest -l server
complete -c speedtest -l exclude
complete -c speedtest -l mini
complete -c speedtest -l source
complete -c speedtest -l timeout
complete -c speedtest -l secure
complete -c speedtest -l no-pre-allocate
complete -c speedtest -l version

