# startpar
# Autogenerated from man page /usr/share/man/man1/startpar.1.gz
complete -c startpar -s p -d 'option, the default is full parallelism'
complete -c startpar -s a -d option
complete -c startpar -s i -d 'can be used to specify another value.   The amount'
complete -c startpar -s t -d 'option is used as buffer timeout'
complete -c startpar -s T -d 'option timeout works more globally'
complete -c startpar -s n -d 'flag is used, output from a running job is prefixed with the name of the prog…'
complete -c startpar -s M -d 'option switches startpar into a make (1) like behaviour'
complete -c startpar -s e -d 'option allows the user to set the location of the system\'s etc configuration …'
complete -c startpar -s f -d 'option causes startpar to copy standard input (stdin) to standard output (std…'
complete -c startpar -s v -d 'option tells startpar to print its name and version number'

