# stterm
# Autogenerated from man page /usr/share/man/man1/stterm.1.gz
complete -c stterm -s a -d 'disable alternate screens in terminal'
complete -c stterm -s c -d 'defines the window class (default $TERM)'
complete -c stterm -s f -d 'defines the  font to use when st is run'
complete -c stterm -s g -d 'defines the X11 geometry string'
complete -c stterm -s i -d 'will fixate the position given with the -g option'
complete -c stterm -s n -d 'defines the window instance name (default $TERM)'
complete -c stterm -s o -d 'writes all the I/O to  iofile'
complete -c stterm -s T -d 'defines the window title (default \'st\')'
complete -c stterm -s t -d 'defines the window title (default \'st\')'
complete -c stterm -s w -d 'embeds st within the window identified by  windowid'
complete -c stterm -s l -d 'use a tty  line instead of a pseudo terminal'
complete -c stterm -s v -d 'prints version information to stderr, then exits'
complete -c stterm -s e -d 'st executes command instead of the shell'

