# stubmaker.1p
# Autogenerated from man page /usr/share/man/man1/stubmaker.1p.gz
complete -c 'stubmaker.1p' -s d -d 'Specifies the directory you wish to output the files to'
complete -c 'stubmaker.1p' -s v -d 'Turns on \\*(L"verbose\\*(R" output during the code stub generation process'
complete -c 'stubmaker.1p' -l help -d 'Outputs a short help message'

