# suspicious-source
# Autogenerated from man page /usr/share/man/man1/suspicious-source.1.gz
complete -c suspicious-source -s h -l help -d 'Show this help message and exit'
complete -c suspicious-source -s v -l verbose -d 'Print more information'
complete -c suspicious-source -s d -l directory -d 'Check the files in the specified directory instead of the current directory'
complete -c suspicious-source -s m -l mimetype -d 'Add mimetype to list of white-listed MIME types'
complete -c suspicious-source -s e -l extension -d 'Add extension to list of white-listed extensions'

