# svcgssd
# Autogenerated from man page /usr/share/man/man8/svcgssd.8.gz
complete -c svcgssd -s f -d 'Runs  rpc'
complete -c svcgssd -s v -d 'Increases the verbosity of the output (can be specified multiple times)'
complete -c svcgssd -s r -d 'If the rpcsec_gss library supports setting debug level, increases the verbosi…'
complete -c svcgssd -s i -d 'If the nfsidmap library supports setting debug level, increases the verbosity…'
complete -c svcgssd -s p -d 'Use principal instead of the default . RI nfs/ FQDN @ REALM '
complete -c svcgssd -s n -d 'Use the system default credentials (host/ FQDN @ REALM ) rather than the defa…'

