# swift
# Autogenerated from man page /usr/share/man/man1/swift.1.gz
complete -c swift -l leave-segments -l help -d 'for more).  post [command-options] [container] [object]'
complete -c swift -s H -d 'The --ignore-mtime option ignores the x-object-meta-mtime metadata entry on t…'
complete -c swift -l version
complete -c swift -s h
complete -c swift -s s -l snet
complete -c swift -s v -l verbose
complete -c swift -s q -l quiet
complete -c swift -s A -l auth
complete -c swift -s U -l user
complete -c swift -s V -l auth-version
complete -c swift -s K -l key
complete -c swift -l os-storage-url
complete -c swift -l os-help -d 'For more options see swift --help and swift --os-help.  EXAMPLE'

