# tagpending
# Autogenerated from man page /usr/share/man/man1/tagpending.1.gz
complete -c tagpending -s n -l noact -d 'Check whether any bugs require tagging, but do not actually do so'
complete -c tagpending -s s -l silent -d 'Do not output any messages'
complete -c tagpending -s v -l verbose -d 'List each bug checked and tagged in turn'
complete -c tagpending -s f -l force -d 'Do not query the \\s-1BTS,\\s0 but (re)tag all bugs closed in the changelog'
complete -c tagpending -l comments -d 'Include the changelog header line and the entries relating to the tagged bugs…'
complete -c tagpending -l no-comments -d 'Do not include changelog entries in the generated mail'
complete -c tagpending -s c -l confirm -d 'Tag bugs as both confirmed and pending'
complete -c tagpending -s t -l to -d 'Parse changelogs for all versions strictly greater than version'
complete -c tagpending -s i -l interactive -d 'Display the message which would be sent to the \\s-1BTS\\s0 and, except when --…'

