# telinit
# Autogenerated from man page /usr/share/man/man8/telinit.8.gz
complete -c telinit -s s -d 'Single user mode boot'
complete -c telinit -s b -d 'Boot directly into a single user shell without running any other startup scri…'
complete -c telinit -s a -d 'The LILO boot loader adds the word "auto" to the command line if it booted th…'
complete -c telinit -s z -d 'The argument to -z is ignored'
complete -c telinit -l version -d 'This argument, when used on its own, displays the current version of init to …'

