# terminus
# Autogenerated from man page /usr/share/man/man1/terminus.1.gz
complete -c terminus -s x -l execute -d 'launches a new Terminus window and execute the remainder of the command line …'
complete -c terminus -s e -l command -d 'launches a new Terminus window and execute the argument inside the terminal'
complete -c terminus -l working-directory -d 'sets the terminal directory to DIRNAME'
complete -c terminus -l no-window -d 'launch Terminus but don\'t open a window'
complete -c terminus -l nobindkey -d 'don\'t try to bind the Quake-mode key (useful for gnome shell)'
complete -c terminus -s h -l help -d 'show this help'
complete -c terminus -s v -l version -d 'show version OPTIONS'
complete -c terminus -l check-gnome -d 'exit if we are running it in Gnome Shell (guake mode should be managed by the…'

