# test-runner
# Autogenerated from man page /usr/share/man/man1/test-runner.1.gz
complete -c test-runner -s c -d 'Specify a runfile to be consumed by the run command'
complete -c test-runner -s d -d 'Dry run mode'
complete -c test-runner -s m -d 'Enable kmemleak reporting (Linux only)'
complete -c test-runner -s g -d 'Create test groups from any directories found while searching for tests'
complete -c test-runner -s o -d 'Specify the directory in which to write test results'
complete -c test-runner -s p -d 'Run script prior to any test or test group'
complete -c test-runner -s P -d 'Run script after any test or test group'
complete -c test-runner -s q -d 'Print only the results summary to the standard output'
complete -c test-runner -s s -d 'Run script as a failsafe after any test is killed'
complete -c test-runner -s S -d 'Execute the failsafe script as username'
complete -c test-runner -s t -d 'Specify a timeout value of n seconds per test'
complete -c test-runner -s u -d 'Execute tests or test groups as username'
complete -c test-runner -s w -d 'Specify the name of the runfile to create'
complete -c test-runner -s x -d 'Execute the pre script as username'
complete -c test-runner -s X -d 'Execute the post script as username'

