# ueberzug
# Autogenerated from man page /usr/share/man/man1/ueberzug.1.gz
complete -c ueberzug -s p -l parser -d 'json: JSON object per line (default)'
complete -c ueberzug -s l -l loader -d 'synchronous ] thread: load image in thread (default)'
complete -c ueberzug -s s -l silent -d 'Print STDERR to /dev/null COPYRIGHT'

