# update-exim4defaults
# Autogenerated from man page /usr/share/man/man8/update-exim4defaults.8.gz
complete -c update-exim4defaults -l help -s h -d 'Print short usage instructions and exit'
complete -c update-exim4defaults -l qflags -d 'Set qflags, special flags given to exim directly after the \\(lq-q\\(rq'
complete -c update-exim4defaults -l queuerunner -d 'Should the init script start one daemon that listens on the smtp port for inc…'
complete -c update-exim4defaults -l queuetime -d 'In which intervals should we run the queue? This passed as option  -q<qflags>…'
complete -c update-exim4defaults -l commonoptions -d 'Options passed both to queue-running and listening instances of Exim'
complete -c update-exim4defaults -l queuerunneroptions -d 'Options only passed to the instance of Exim running the queue'
complete -c update-exim4defaults -l smtplisteneroptions -d 'Options only passed to the instance of Exim listening on the SMTP port'
complete -c update-exim4defaults -l force -s f -d 'Without this option  update-exim4defaults exits with an error if at least one…'
complete -c update-exim4defaults -l remove-common -d 'Try to remove the given option from COMMONOPTIONS'
complete -c update-exim4defaults -l remove-queue -d 'Try to remove the given option from QUEUERUNNEROPTIONS'
complete -c update-exim4defaults -l remove-smtp -d 'Try to remove the given option from SMTPLISTENEROPTIONS'
complete -c update-exim4defaults -o 'q<qflags>time' -d 'to Exim, e. g.  -q30m or -qq1h'
complete -c update-exim4defaults -l remove-commands -d 'additionally remove whitespace at the beginning and the end of the option and…'
complete -c update-exim4defaults -l init -d 'create a default /etc/default/exim4 file and exit immediately.  Unless'
complete -c update-exim4defaults -l remove-something

