# uupdate
# Autogenerated from man page /usr/share/man/man1/uupdate.1.gz
complete -c uupdate -l no-conf -l noconf -d 'Do not read any configuration files'
complete -c uupdate -l upstream-version -s v -d 'Specify the version number of the upstream package explicitly'
complete -c uupdate -l force-bad-version -s b -d 'Force a version number to be less than the current one (e. g'
complete -c uupdate -l rootcmd -s r -d 'Specify the command to be used to become root to build the package and is pas…'
complete -c uupdate -l pristine -s u -d 'Treat the source as pristine upstream source and symlink to it from <package>…'
complete -c uupdate -l no-pristine -d 'Do not attempt to make a <package>_<version>. orig. tar. gz symlink'
complete -c uupdate -l symlink -s s -d 'Simply create a symlink when moving a new upstream . tar'
complete -c uupdate -l no-symlink -d 'Copy the upstream . tar'
complete -c uupdate -l find -s f -d 'Find all upstream tarballs in . / which match <pkg>_<version>. orig. tar'
complete -c uupdate -l verbose -d 'Give verbose output'
complete -c uupdate -l help -s h -d 'Display a help message and exit successfully'
complete -c uupdate -l version -d 'Display version and copyright information and exit successfully'

