# vim-addon-manager
# Autogenerated from man page /usr/share/man/man1/vim-addon-manager.1.gz
complete -c vim-addon-manager -s h -l help -d 'show this usage message and exit'
complete -c vim-addon-manager -s q -l query -d 'be quiet and make the output more parseable (for "status")'
complete -c vim-addon-manager -s r -l registry-dir -d 'set the registry directory (default: /usr/share/vim/registry)'
complete -c vim-addon-manager -s s -l source-dir -d 'set the addons source directory (default: /usr/share/vim/addons)'
complete -c vim-addon-manager -s t -l target-dir -d 'set the addons target directory (default: $HOME/. vim)'
complete -c vim-addon-manager -s v -l verbose -d 'increase verbosity level'
complete -c vim-addon-manager -s z -l silent -d 'silent mode: suppress most of the output'
complete -c vim-addon-manager -s y -l system-dir -d 'set the system-wide target directory (default: /var/lib/vim/addons)'
complete -c vim-addon-manager -s w -l system-wide -d 'set the addons target directory to the system-wide target directory, possibly…'

