# what-patch
# Autogenerated from man page /usr/share/man/man1/what-patch.1.gz
complete -c what-patch -s h -l help -d 'Display a help message and exit'
complete -c what-patch -s v -d 'Enable verbose mode'

