# who-uploads
# Autogenerated from man page /usr/share/man/man1/who-uploads.1.gz
complete -c who-uploads -s M -l max-uploads -d 'Specify the maximum number of uploads to display for each package; the defaul…'
complete -c who-uploads -l keyring -d 'Add keyring to the list of keyrings to be searched for the uploader\'s GPG key'
complete -c who-uploads -l no-default-keyrings -d 'By default, who-uploads uses the three Debian keyrings /usr/share/keyrings/de…'
complete -c who-uploads -l date -d 'Show the date of the upload alongside the uploader\'s details'
complete -c who-uploads -l nodate -l no-date -d 'Do not show the date of the upload alongside the uploader\'s details'
complete -c who-uploads -l no-conf -l noconf -d 'Do not read any configuration files'
complete -c who-uploads -l help -s h -d 'Display a help message and exit successfully'
complete -c who-uploads -l version -d 'Display version and copyright information and exit successfully'

