# who-permits-upload
# Autogenerated from man page /usr/share/man/man1/who-permits-upload.1.gz
complete -c who-permits-upload -l dmfile -s d -d 'Retrieve the \\s-1DM\\s0 permission file from the supplied \\s-1URL'
complete -c who-permits-upload -l help -s h -d 'Display a usage summary and exit'
complete -c who-permits-upload -l keyring -s s -d 'Use the supplied GnuPG keyrings to look-up \\s-1GPG\\s0 fingerprints from the \\…'
complete -c who-permits-upload -l search -d 'Modify the look-up behavior'

