# whodepends
# Autogenerated from man page /usr/share/man/man1/whodepends.1.gz
complete -c whodepends -l help -s h -d 'Show a brief usage message'
complete -c whodepends -l version -s v -d 'Show version and copyright information'

