# wnpp-alert
# Autogenerated from man page /usr/share/man/man1/wnpp-alert.1.gz
complete -c wnpp-alert -l diff -s d -d 'If the $XDG_CACHE_HOME/devscripts directory exists, compare the output of wnp…'
complete -c wnpp-alert -l help -s h -d 'Show a summary of options'
complete -c wnpp-alert -l version -s v -d 'Show version and copyright information.  SEE ALSO https://www. debian'

