# wnpp-check
# Autogenerated from man page /usr/share/man/man1/wnpp-check.1.gz
complete -c wnpp-check -l exact -s e -d 'Require an exact package name match, rather than the default substring match'
complete -c wnpp-check -l help -s h -d 'Show a summary of options'
complete -c wnpp-check -l version -s v -d 'Show version and copyright information.  SEE ALSO https://www. debian'

