# wrap-and-sort
# Autogenerated from man page /usr/share/man/man1/wrap-and-sort.1.gz
complete -c wrap-and-sort -s h -l help -d 'Show this help message and exit'
complete -c wrap-and-sort -s a -l wrap-always -d 'Wrap all package lists in the Debian control file even if they do not exceed …'
complete -c wrap-and-sort -s s -l short-indent -d 'Only indent wrapped lines by one space (default is in-line with the field nam…'
complete -c wrap-and-sort -s b -l sort-binary-packages -d 'Sort binary package paragraphs by name'
complete -c wrap-and-sort -s k -l keep-first -d 'When sorting binary package paragraphs, leave the first one at the top'
complete -c wrap-and-sort -s n -l no-cleanup -d 'Do not remove trailing whitespaces'
complete -c wrap-and-sort -s t -l trailing-comma -d 'Add a trailing comma at the end of the sorted fields'
complete -c wrap-and-sort -s d -l debian-directory -d 'Location of the debian directory (default: . /debian)'
complete -c wrap-and-sort -s f -l file -d 'Wrap and sort only the specified file'
complete -c wrap-and-sort -s v -l verbose -d 'Print all files that are touched'
complete -c wrap-and-sort -l max-line-length -d 'Set the maximum allowed line length'
complete -c wrap-and-sort -s N -l dry-run -d 'Do not modify any file, instead only print the files that would be modified'
complete -c wrap-and-sort -l experimental-rts-parser -d 'Enable the experimental round-trip safe parser'

