# x-window-manager
# Autogenerated from man page /usr/share/man/man1/x-window-manager.1.gz
complete -c x-window-manager -l help -d 'Show a summary of the command line options available  and exit'
complete -c x-window-manager -l version -d 'Show the version of the program and exit'
complete -c x-window-manager -l replace -d 'Replace the currently running window manager'
complete -c x-window-manager -l config-file -d 'Specify the path to the config file to use'
complete -c x-window-manager -l reconfigure -d 'If Openbox is already running on the display, tell it to  reload its configur…'
complete -c x-window-manager -l restart -d 'If Openbox is already running on the display, tell it to  restart'
complete -c x-window-manager -l exit -d 'Exit Openbox'
complete -c x-window-manager -l sm-disable -d 'Do not connect to the session manager'
complete -c x-window-manager -l sync -d 'Run in synchronous mode (for debugging)'
complete -c x-window-manager -l startup -d 'Run CMD after starting'
complete -c x-window-manager -l debug -d 'Display debugging output'
complete -c x-window-manager -l debug-focus -d 'Display debugging output for focus handling'
complete -c x-window-manager -l debug-session -d 'Display debugging output for session management'

