# xdelta3
# Autogenerated from man page /usr/share/man/man1/xdelta3.1.gz
complete -c xdelta3 -s 0 -s 9 -d 'compression level'
complete -c xdelta3 -s c -d 'use stdout'
complete -c xdelta3 -s d -d decompress
complete -c xdelta3 -s e -d compress
complete -c xdelta3 -s f -d 'force overwrite'
complete -c xdelta3 -s h -d 'show help'
complete -c xdelta3 -s q -d 'be quiet'
complete -c xdelta3 -s v -d 'be verbose (max 2)'
complete -c xdelta3 -s V -d 'show version'
complete -c xdelta3 -s B -d 'RI bytes source window size'
complete -c xdelta3 -s W -d 'RI bytes input window size'
complete -c xdelta3 -s P -d 'RI size compression duplicates window'
complete -c xdelta3 -s I -d 'RI size instruction buffer size (0 = unlimited)'
complete -c xdelta3 -s s -d 'RI source source file to copy from (if any)'
complete -c xdelta3 -s S -d 'enable/disable secondary compression'
complete -c xdelta3 -s N -d 'disable small string-matching compression'
complete -c xdelta3 -s D -d 'disable external decompression (encode/decode)'
complete -c xdelta3 -s R -d 'disable external recompression (decode)'
complete -c xdelta3 -s n -d 'disable checksum (encode/decode)'
complete -c xdelta3 -s C -d 'soft config (encode, undocumented)'
complete -c xdelta3 -s A -d 'disable/provide application header (encode)'
complete -c xdelta3 -s J -d 'disable output (check/compute only)'
complete -c xdelta3 -s T -d 'use alternate code table (test)'

