# xdelta-config
# Autogenerated from man page /usr/share/man/man1/xdelta-config.1.gz
complete -c xdelta-config -l version -d 'Print the currently installed version of xdelta on the standard output'
complete -c xdelta-config -l libs -d 'Print the linker flags that are necessary to link a xdelta program'
complete -c xdelta-config -l cflags -d 'Print the compiler flags that are necessary to compile a xdelta program'
complete -c xdelta-config -l prefix -d 'If specified, use PREFIX instead of the installation prefix that xdelta was b…'
complete -c xdelta-config -l exec-prefix -d 'If specified, use PREFIX instead of the installation exec prefix that xdelta …'

