# xdelta
# Autogenerated from man page /usr/share/man/man1/xdelta.1.gz
complete -c xdelta -o '0..9' -d 'Set the zlib compression level.   Zero indicates no compression'
complete -c xdelta -s h -l help -d 'Print a short help message and exit'
complete -c xdelta -s q -l quiet -d 'Quiet.   Surpresses several warning messages'
complete -c xdelta -s v -l version -d 'Print the Xdelta version number and exit'
complete -c xdelta -s V -l verbose -d 'Verbose.   Prints a bit of extra information'
complete -c xdelta -s n -l noverify -d 'No verify'
complete -c xdelta -o mSIZE -l maxmem -d 'Set an upper bound on the size of an in-memory page cache'
complete -c xdelta -s s -d 'Set the block size, unless it was hard coded (20% speed improvement)'
complete -c xdelta -s p -l pristine -d 'Disable the automatic decompression of gzipped inputs, to prevent unexpected …'

